model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/elements/rom.def

- Description of Issue: This property is not defined and not implemented
so it should be hidden.
- Description of Resolution: Add property visibility in rom.def.
- Bugzilla(s) Resolved: 144383

BIRT bug fixes (model property hidden in designer.)

---

engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/PDFPage.java

fix bug 456545 defensive code to avoid NPE on null hyperlink

fix bug 456545 defensive code to avoid NPE

---

engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/TableLayout.java

For the row height specified as 100%, it is wrong calcualted to 0.

Fixed bug 457088.

---

UI/org.eclipse.birt.report.debug.ui/build.properties

[ERROR] Failed to execute goal
org.eclipse.tycho:tycho-source-plugin:0.21.0:plugin-source (plugin-source)
on project org.eclipse.birt.report.debug.ui:
By removing .cvsignore from src.includes

Fix this compile error.

---

engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/executor/optimize/ExecutionOptimize.java

The top level Group header should stretch over to preceding page for the the list of data that does not fit in one page.  At some point it happens in Auto layout but Fixed layout works fine.
And revert commit f49fecb31fd8c3e7a1ce872e06e719e2551995e7

Internal refactor apis for enchancement

---

UI/org.eclipse.birt.report.designer.ui.samplesview/plugin.xml
features/org.eclipse.birt.example.feature/feature.xml
features/org.eclipse.birt.nl.feature/feature.xml

Remove Report examples view from BIRT designer 
Note: following plugins need to remove from BIRT open source:
org.eclipse.birt.report.designer.samplereports
org.eclipse.birt.report.designer.ui.samples.ide
org.eclipse.birt.report.designer.ui.samplesview
Signed-off-by: Yuxuan Dai <ydai@actuate.com>

Summary: Remove Report examples view from BIRT designer 

---

data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/olap/impl/query/CubeQueryDefinition.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/data/dte/ReportQueryBuilder.java

Data Engine uses the new Model API for query time join to create QueryDefinitions

Engine adds join information when creating queries

---

UI/org.eclipse.birt.report.designer.ui.views/src/org/eclipse/birt/report/designer/ui/views/attributes/AbstractPageGenerator.java
UI/org.eclipse.birt.report.designer.ui.views/src/org/eclipse/birt/report/designer/ui/views/attributes/BasePageGenerator.java
UI/org.eclipse.birt.report.designer.ui.views/src/org/eclipse/birt/report/designer/ui/views/attributes/IPageGeneratorHelper.java

pages.  Move the page generator helper code deeper in the class hierarchy
so it can be applied to more types of report items.

Allow for customization of extended items to have additional property

---

UI/org.eclipse.birt.report.designer.ui.cubebuilder/src/org/eclipse/birt/report/designer/ui/cubebuilder/provider/TabularMeasureGroupNodeProvider.java

- Description of Issue: BIRT extensions can modify the model to have
measures outside of cubes.  So there is an exception raised from the
TabularMeasureGroupNodeProvider because the container is not a cube.
- Description of Resolution: Support container that is not a cube.
- Regression ( Yes/No ): No
- Code owner Team: BIRT
- Code Reviewers:
- Project ID:
- Manual Test Description: Debug in dev env
- Tests Automated Cases Executed:
- Special Notes:

- Summary: Support Tabular Measure Group containers that are not cubes.

---

chart/org.eclipse.birt.chart.ui.extension/src/org/eclipse/birt/chart/ui/swt/wizard/data/BaseDataDefinitionComponent.java

When expression for series starts with data, disable aggregation function
combo box.
Otherwise, enable normal behavior.

Chart Builder - support extended pre-defined aggregation

---

engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/executor/OnPageBreakLayoutPageHandle.java

1. Bug was introduced in fixing Bug 431702 (Performance bottleneck in engine executor because of using arrayList.contains() method a lot.) The committer used a TreeSet to improve performance but does not implement Comparable interface, which result in ClassCastException
2. A linkedHashedSet will be enough for improving performance of contains method and simultaneously maintains the insertion order implied by arrayList.add() method

Bug 481003 - Report onPageEnd and onPageStart scripts broken at report render time with ClassCastException

---

engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXCanvas.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/emitter/PageDeviceRender.java

- Description of Issue: Background image overflow outside page
- Description of Resolution: limit image size
- TED(s) Resolved: BIRT-1235
- Code Owner Team: BIRT
- Code Reviewers: 
- Project ID:
- Tests: 
Ran locally
- Tests Automated (Yes/No, if “No”, then explain why):
No, only through report generation
- Special Notes:

- Summary: Background image not sized properly in PPTX

---

core/org.eclipse.birt.core.tests/test/org/eclipse/birt/core/format/DateFormatterTest.java
core/org.eclipse.birt.core/src/org/eclipse/birt/core/format/DateFormatter.java

- Description of Issue:  The new ibm.icu has a different datetime format
- Description of Resolution: customize to a predefine format on english
- bug Resolved: bug 478576
- Tests: 
Ran locally
- Tests Automated (Yes/No, if “No”, then explain why):
Yes

- Summary: Date Format changed on default behavior

---

UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/util/ExpressionUtility.java

setBindingColumnExpression.  This is used in the case where the binding
column is actually a measure.

Create function setBindingMeasureExpression similar to

---

chart/org.eclipse.birt.chart.reportitem.ui/src/org/eclipse/birt/chart/reportitem/ui/ChartExpressionButton.java
chart/org.eclipse.birt.chart.reportitem.ui/src/org/eclipse/birt/chart/reportitem/ui/ReportDataServiceProvider.java

indicator, then the corresponding column header expression should be a
data expression ( i.e. not a row expression )

If the column binding info expression property begins with a measure

---

core/org.eclipse.birt.core/src/org/eclipse/birt/core/format/DateFormatter.java

- Description of Issue:  unformatted datetime does not work correctly
- Description of Resolution: include case on predefine patterns

- Summary: Date Missing case for DateTimeFormat

---

UI/org.eclipse.birt.report.designer.ui.ide/src/org/eclipse/birt/report/designer/ui/editors/ReportEditorProxy.java

already disposed.  To avoid an error message that is not useful, simply
return an instance of NullEditorInput so the property tester doesn't
complain.

report editor input property is "tested" during shutdown after being

---

features/org.eclipse.birt.feature/feature.xml

Export to Excel in XLS & XLSX formats missing in BIRT Open Source v.4.6
modified feature.xml file to make org.eclipse.birt.feature includes xls & xlsx plugins. 

Eclipse bug 483950

---

UI/org.eclipse.birt.report.debug.ui/src/org/eclipse/birt/report/debug/ui/DebugUI.java

NPE when attempting to create debug configuration
Description: initialize the class before referencing static variables
Reported by: Jane Tatchell

NPE when attempting to create debug configuration

---

viewer/org.eclipse.birt.report.viewer/jettyhome/etc/jetty.xml

For Jetty 9 - you will need to edit jetty.xml which is located
$Jetty_Home/etc

Remove Jetty icon in opensource 4.6 for report viewer

---

data/org.eclipse.birt.data.oda.mongodb/src/org/eclipse/birt/data/oda/mongodb/internal/impl/MDbMetaData.java

Fixed MongoDB ODA plugin issue with report failing with "Column binding
"x.y" has referred to a data set column "x.y" which does not exist"
error for empty collections with subdocument fields.

MongoDB ODA issue with empty collections with subdocument fields

---

data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/api/aggregation/AggregationManager.java

Removed unsupported aggregation function RANK and RUNNINGSUM from
aggregation builder

Functions used in measure dialogue cause error in chart & xtab

---

xtab/org.eclipse.birt.report.item.crosstab.core/src/org/eclipse/birt/report/item/crosstab/core/de/internal/CrosstabModelUtil.java
xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/internal/ui/dialogs/CrosstabBindingDialogHelper.java

do not include extended entries in the expression
choices drops down.  Only include normal category columns.

For crosstab binding, when we create new aggregation,

---

chart/org.eclipse.birt.chart.reportitem.ui/src/org/eclipse/birt/chart/reportitem/ui/ChartReportItemBuilderImpl.java
chart/org.eclipse.birt.chart.ui.extension/src/org/eclipse/birt/chart/ui/swt/wizard/data/BaseDataDefinitionComponent.java

expression builder of "Category (X) Series" and "Optional Y Series
Grouping." When the user selected "Available Column BIndings" and "Chart"
the far right column should not show invalid items.  Invalid items are
items that can not be chosen from the dropdown list and can not be dragged
and dropped into the expression field.

This fix is for the "Select Data" page of the chart builder and for the

---

xtab/org.eclipse.birt.report.item.crosstab.core/src/org/eclipse/birt/report/item/crosstab/core/de/ComputedMeasureViewHandle.java
xtab/org.eclipse.birt.report.item.crosstab.core/src/org/eclipse/birt/report/item/crosstab/core/util/CrosstabUtil.java

and only if those measures are not from data cubes and they also have
their own aggregation.

We allow for ComputedMeasureView to have direct reference to measures if

---

chart/org.eclipse.birt.chart.reportitem/src/org/eclipse/birt/chart/reportitem/AbstractChartBaseQueryGenerator.java

Fixed a previous NPE protection which was implied too early. 

Sorting not applied on X Series when optional Y series is enabled.

---

core/org.eclipse.birt.core/src/org/eclipse/birt/core/btree/BTree.java

Issue: Failed to close the indexes java.io.IOException
solution:  btree removeEldestEntry have to pick the value to remove instead of
node.  When node is lock and value is dirty

Summary: Failed to close the indexes java.io.IOException

---

data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/TotalSum.java
data/org.eclipse.birt.data.tests/test/org/eclipse/birt/data/engine/aggregation/TotalTest.java

Fixed issue with Double.NaN and Double.Infinity handling in TotalSum. In particular, this solves NumberFormatException thrown when NaN is encountered and some side effects caused by using NaN/Infinity in operations involving Double and BigDecimal.

Fixed issue with Double.NaN and Double.Infinity handling in TotalSum

---

1.txt
core/org.eclipse.birt.core/src/org/eclipse/birt/core/data/DataTypeUtil.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/calculator/BigDecimalCalculator.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/calculator/BooleanCalculator.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/calculator/CalculatorFactory.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/calculator/DateCalculator.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/calculator/NumberCalculator.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/calculator/StringCalculator.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/RunningAccumulator.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/SummaryAccumulator.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/TotalAve.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/TotalIrr.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/TotalMedian.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/TotalMirr.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/TotalMode.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/TotalMovingAve.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/TotalNpv.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/TotalRunningNpv.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/TotalRunningSum.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/TotalStdDev.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/TotalSum.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/TotalVariance.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/TotalWeightedAve.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/rank/PercentileAccumulator.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/rank/TotalPercentSum.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/rank/TotalPercentile.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/rank/TotalQuartile.java
data/org.eclipse.birt.data.tests/test/org/eclipse/birt/data/engine/aggregation/TotalTest.java

* Create calculator based on the aggregate function return type.
* Left the only calculator factory method: the factory is picked based
on data type from supported list.
* Removed all value conversions from calculators in favour of simple
cast.
* Made more extensive use of DataTypeUtil library.
* Updated all aggregate function classes to convert values passed to
calculator using getTypedObject() method of the calculator.
* Double calculator is still the default one. This comes with automated
NaN and Infinity handling.
* Sum value can be null now. Note that data export may look slightly
different due to that: it actually exports nulls where appropriate and
not 0s as before. Otherwise nulls are ignored in calculations.
* Updated unit tests accordingly.
Signed-off-by: Serguei Krivtsov …

Aggregation calculators enhancements

---

core/org.eclipse.birt.core/src/org/eclipse/birt/core/data/DataTypeUtil.java
data/org.eclipse.birt.data.tests/test/org/eclipse/birt/data/engine/aggregation/TotalTest.java

Recent aggregate functions/calculators enhancement caused some aggregate
functions result to be Double even for Date operands.
Also added a unit test for AVE(Date).

Implemented Double to Date conversion in DataTypeUtil

---

core/org.eclipse.birt.core.tests/test/org/eclipse/birt/core/data/DataTypeUtilTest.java
core/org.eclipse.birt.core/src/org/eclipse/birt/core/data/DataTypeUtil.java

Recent aggregate functions/calculators enhancement caused certain
aggregate functions results to be Double even for Date operands. Similar
to toDate conversion, toSqlDate and toSqlTime must be also updated
accordingly.
Also added unit tests for to-date and to-time conversion.

Implemented Double to java.sql.Date and to java.sql.Time conversion to DataTypeUtil

---

UI/org.eclipse.birt.report.debug.ui/src/org/eclipse/birt/report/debug/ui/launching/ReportAdvancedLauncherTab.java
viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/utility/ParameterAccessor.java
viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/pages/layout/FramesetFragment.jsp
viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/pages/layout/RequesterFragment.jsp
viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/pages/layout/RunFragment.jsp

DefaultContentProvider was removed in Neon causing compile error.
This class had only empty methods to satisfy the interface.  So, the solution is to simply move these 2 empty methods into the class ReportAdvancedLauncherTab.PluginContentProvider.

Bugzilla 490551 UI depends on obsolete eclipse class.

---

chart/org.eclipse.birt.chart.device.swt/src/org/eclipse/birt/chart/device/swt/SwtRendererImpl.java

with Eclipse MAT.
In the setProperty method of the SWT renderer implementation, check for
sProperty equals IDeviceRenderer.EXPECTED_BOUNDS, and if so, set clipping
on the graphics context.

Bugzilla 483851 - Recent versions of BIRT/Eclipse show a blank pie chart

---

pom.xml

This allows the user to clone and checkout the source code of Birt
without knowing where the repository is. See:
https://wiki.eclipse.org/PDE/UI/SourceReferences
One use case is to right-click on a plug-in under the Plug-in
dependencies in Package Explorer view and select Import from Repository.
Note that for this EGit needs to be installed.
Another use case is to go to
File > Import > Plug-In Development > Plug-ins and Fragments then select
Projects from a repository.
What this patch does is to let Tycho generate the source references in
the MANIFEST.MF of the built jars. So to test this patch, one can build
the update site locally and inspect the manifests of the (non-source)
jars.
Also see:
http://download.eclipse.org/releases/staging/buildInfo/reporeports/reports/esdata.txt …

Add SourceReferences to plugins

---

engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/writer/Presentation.java
model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/util/DimensionUtil.java

properties given in pixels need to be converted into points, the max height of the slide was reach and it corrupt the slide, so set the boundary

fix certain report design that does not convert properly in PPTX

---

build/birt-packages/pom.xml
build/org.eclipse.birt.api/pom.xml
build/org.eclipse.birt.p2updatesite/pom.xml
build/org.eclipse.birt.sdk/pom.xml

Updated org.eclipse.birt.build-parent version to 4.6.0-SNAPSHOT in all
subpackages

Synchronized build parent package version

---

engine/org.eclipse.birt.report.engine.fonts/fontsConfig.xml

Bug 478548 - fontsConfig.xml is missing system default font paths.

---

pom.xml

Allow tycho-surefire plugin to detect required JUnit runner automatically. Also bumped up surefire-report plugin version to the most current.

Remove tycho-surefire dependency on JUnit 3

---

pom.xml

Updated jacoco to the most current release version. Also changed jacoco configuration to more generic. This solved the issue with generating coverage report in Jenkins builds.

Updated jacoco configuration

---

data/org.eclipse.birt.me.prettyprint.hector/lib/hector-LICENSE
data/org.eclipse.birt.me.prettyprint.hector/lib/slf4j-license.html
data/org.eclipse.birt.me.prettyprint.hector/pom.xml

When dialog is opened select Cassandra Scripted Data Source. Result. there
is the error message: "Unable to find Hector client library jars to
support Cassandra Scripted Data Source."
Solution: Modify build script to add missing files.
Include dependencies jar files and license in lib folder.

Summary: An error to add Cassandra Scripted Data Source.

---

testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/ChartTestCase.java
testsuites/org.eclipse.birt.tests.core/src/utility/ImageUtil.java

Reliably calculate chart test data location both on Windows and Linux

---

data/org.eclipse.birt.data.tests/META-INF/MANIFEST.MF
data/org.eclipse.birt.data.tests/test/org/eclipse/birt/data/engine/odaconsumer/LargeObjectTest.java
data/org.eclipse.birt.report.data.oda.jdbc.tests/test/org/eclipse/birt/report/data/oda/jdbc/ConnectionTest.java
engine/org.eclipse.birt.report.engine.tests/META-INF/MANIFEST.MF
engine/org.eclipse.birt.report.engine.tests/pom.xml
engine/org.eclipse.birt.report.engine.tests/test/org/eclipse/birt/report/engine/api/RenderTaskTest.java
engine/org.eclipse.birt.report.engine.tests/test/org/eclipse/birt/report/engine/api/impl/DataExtractionTaskTest.java
engine/org.eclipse.birt.report.engine.tests/test/org/eclipse/birt/report/engine/api/impl/LoggerSettingTest.java

Fixed several data and engine unit tests

Miscellaneous unit test fixes

---

UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/core/commands/PasteReportItemThemeCommand.java
UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/util/DNDUtil.java

In a library, create two themes.
Create a report item theme in the first theme.
1.
Click the report item theme and drag it to the second theme.
Expected:
The report item theme moves from the first theme to the second theme.
Actual:
The report item theme does not move.
2.
Right-click the report item theme and choose Copy.
Right-click the second theme and choose Paste.
Expected:
A copy of the report item theme appears in the second theme.
Actual:
A copy of the report item theme appears in the Themes slot at the same
level as the main themes.
3.
Right-click the report item theme and choose Cut.
Right-click the second theme and choose Paste.
Expected:
The report item theme is no longer in the first theme and appears in the
second theme.
Actual:
The report item theme reappears in the first …

Fixing report item theme cut/copy/paste and drag/drop.

---

engine/org.eclipse.birt.report.engine.emitter.postscript/src/org/eclipse/birt/report/engine/emitter/postscript/truetypefont/TrueTypeFont.java

Added the condition to take care of this specific case.

Postscript on linux is not able to find bold nbsp font.

---

data/org.eclipse.birt.report.data.oda.jdbc.tests/test/org/eclipse/birt/report/data/oda/jdbc/ConnectionTest.java
data/org.eclipse.birt.report.data.oda.jdbc.tests/test/org/eclipse/birt/report/data/oda/jdbc/TestUtil.java
data/org.eclipse.birt.report.data.oda.jdbc/src/org/eclipse/birt/report/data/oda/jdbc/Connection.java
data/org.eclipse.birt.report.data.oda.jdbc/src/org/eclipse/birt/report/data/oda/jdbc/utils/JDBCDriverInfoManager.java

NPE in JDBCDriverInfoManager
remove assertion for url != null in Connection
adding test for jndi connection without any other properties
maybe you use the test without the other changes to see that birt has changed its behaviour with jndi name only connection since version 4.4.2

fixes NPE and wrong assumptions for an assert

---

build/org.eclipse.birt.sdk/pom.xml

build/org.eclipse.birt.sdk/pom.xml has an extra <project> block at the bottom. It looks like a copy-paste error and can be removed.

Fixed a pom file, which wasn't well-formed XML

---

pom.xml

Minimal required changes to fix Oxygen profile build: some transient
dependency now requires EMF 2.13.

Fix master branch build

---

core/org.eclipse.birt.core.tests/test/org/eclipse/birt/core/archive/ArchiveUtilTest.java
core/org.eclipse.birt.core/src/org/eclipse/birt/core/archive/ArchiveUtil.java

Fixed this issue by adding encoding for '*'.

Failed to generate .data file when datadesign includes a dataset with special characters

---

engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/writer/AbstractWordXmlWriter.java

This enhancement is to crop the words that exceed the width of the cell.
If the property is not set, it will wrap around cell and expand the
height of the row and table changing the overall layout

Overflow hidden property does not exist on table cell in DOCX

---

engine/org.eclipse.birt.report.engine.emitter.config.pptx/src/org/eclipse/birt/report/engine/emitter/config/pptx/PPTXEmitterDescriptor.java
engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXRender.java

Revert configuration option commit:
824345a6e3d1ff2b9b8ba8e0948412e95a3ca82b
and revert new change commit: 7d46aaaf5730dc312915c84492f60ce62eb5fbbe
The function reorderVisually runs inside that flag that put the proper
layout of multiple boxes when it is in a line area.  We removed it for a smaller issue

Span tag was running properly on 4.2, it required BIDI flag to be true

---

model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/elements/rom.def
model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/metadata/ElementDefn.java

1. Element MasterPage has its own height and width property, during ElementDefn.buildCachedPropertyDefns( ), height and
width from style will over write the original property, and hence lose
those original properties.
2. define allowed units for simpleMasterPage footer and header

Changes made for masterpage in properties corrupted in layout page

---

model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/metadata/ElementDefn.java

Element CSS style width and height should not override masterpage width
and height

Master page cannot use relative units

---

UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/ui/views/attributes/providers/ChoiceSetFactory.java
xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/ui/views/dialogs/CrosstabFilterConditionBuilder.java

Remove TopN/BottomN/Top%/Bottom % from filter options in xtab

Remove TopN/BottomN/Top%/Bottom % from filter options in xtab

---

data/org.eclipse.birt.data.tests/META-INF/MANIFEST.MF

Bumped up required execution environment version for data engine tests.
Older Derby 10.8 used by the test was incompatible with newer 10.11 test
db format, which caused multiple test failires.

Multiple data engine unit tests failed due to older Derby

---

engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/style/TextStyle.java

Links are not underlined in pdf output if the links text contain spaces
and is justified when it is more than one line.

Bookmark is not underline on PDF emitter on spec setting

---

engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLReportEmitter.java

Html button defined with no width and display selected as 'block', will
use a div tag as container. since there is no width set, by default div
will occupy entire width of web page and hence it seems like the button
is being spread across web page.
A script has been added to resize the tab in this particular scenario,
so that when no width is specified it will resize based on the contents
inside div tab.
Signed-off-by: pvadanap <pvadanap@PVADANAP1LCWXX1.opentext.net>

Customize color of a HTML button does not work as expected.

---

chart/org.eclipse.birt.chart.reportitem.ui/src/org/eclipse/birt/chart/reportitem/ui/ChartReportItemUIImpl.java

-Description of Issue:
when a chartItem present in a library is modifed then NPE is thrown once
we refresh the library or if we open the reportdesing is reopened.
-Description of Resolution:
Added not null check.
Signed-off-by: rrimmana rrimmana@RRIMMANA4J5LX52.opentext.net

Altering a library causes null pointer when reloading in a report

---

build/birt-packages/birt-integration-test/pom.xml
data/org.eclipse.birt.data.oda.mongodb.ui/META-INF/MANIFEST.MF
data/org.eclipse.birt.data.oda.mongodb/META-INF/MANIFEST.MF
pom.xml
viewer/org.eclipse.birt.jetty.overlay/META-INF/MANIFEST.MF
viewer/org.eclipse.birt.report.viewer/META-INF/MANIFEST.MF
viewer/org.eclipse.birt.report.viewer/jettyhome/etc/jetty-selector.xml
viewer/org.eclipse.birt.report.viewer/jettyhome/etc/jetty.xml
viewer/org.eclipse.birt.report.viewer/pom.xml

* Jetty 9.4+ is now required for Oxygen, so upgraded Jetty to 9.4.1.
This fixes the report preview issue.
* Restricted Jetty to specific version for each profile. This is
required for suporting three different profiles for three different
releases. This also allowed to remove its version from build files.
* Upgraded Tycho to version 1.0.0 due to a Tycho 0.25.0 bug, which broke
the BIRT build when usign the latest Eclipse Oxygen milestones.

Upgrade Jetty to 9.4.1

---

model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/ModuleOption.java

…o remove Locale.
Signed-off-by: Ravikiran Katneni <rkatneni@opentext.com>

BIRT getMessage("key") call does not take the defined locale in Preview settings but the default en_US

---

LICENSE

According to http://www.eclipse.org/birt/about/ BIRT is licensed under the Eclipse Public License.
Including this license file makes that assertion more visible.

Declaring the license

---

pom.xml

Later Orbit drops contain two MongoDB bundle versions. Restrict MongoDB
budle version using a filter to avoid two bundles to be included in
plugins.

Restrict MongoDB bundle version

---

core/org.eclipse.birt.core/build.properties

Hello BIRT Committers,
This pull request adds missing entry for the ScriptEngineFactory.exsd in build.properties.
Fixes https://bugs.eclipse.org/bugs/show_bug.cgi?id=520124.
I had found this out some days ago and asked for it on the mailing list.
http://dev.eclipse.org/mhonarc/lists/birt-dev/msg10988.html
Please let me know what you think.
Regards,
Zorawar

Bug 520124: Add missing ScriptEngineFactory schema file entry

---

chart/org.eclipse.birt.chart.engine/src/org/eclipse/birt/chart/internal/datafeed/DataProcessor.java
chart/org.eclipse.birt.chart.engine/src/org/eclipse/birt/chart/util/ChartUtil.java
chart/org.eclipse.birt.chart.ui.extension/src/org/eclipse/birt/chart/ui/swt/composites/ExternalizedTextEditorComposite.java

If the chart legend string contains an '=' symbol, it will truncate.
-Description of Resolution:
For y optional generateed series name with having “=” to be rendered
correctly we had prefixed '='.
Signed-off-by: rrimmana <rrimmana@RRIMMANA4J5LX52.opentext.net>

-Description of Issue: chart legend string contains an '=' symbol, it will get truncated

---

engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLReportEmitter.java
engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/util/HTMLEmitterUtil.java

Chrome
Dont provide alt attribute to the img element in single metric.
Signed-off-by: rvasanth <rvasanth@RVASANTHBZ44NV1.opentext.net>

Broken image icon is not displaying in Mozilla, but it is displaying in

---

data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/executor/transform/SimpleResultSet.java

Fixed the inverted / wrong-way-round assertion reported in bug [472025 ](https://bugs.eclipse.org/bugs/show_bug.cgi?id=472025) and [512004](https://bugs.eclipse.org/bugs/show_bug.cgi?id=512004).

Fixing Bug 472025 - Wrong assert statement in SimpleResultSet

---

data/org.eclipse.birt.data.oda.mongodb.ui/src/org/eclipse/birt/data/oda/mongodb/ui/impl/MongoDBDataSourcePageHelper.java
data/org.eclipse.birt.data.oda.mongodb/src/org/eclipse/birt/data/oda/mongodb/impl/MongoDBDriver.java

Issue: Once the properties are set in the UI they are being used irrespective of kerberos checkbox selection and Mongodb Uri radio button selection while creating a Mongodb source in Birt
Resolution:
1.Modified the properties which are received from UI in MongoDBDriver.java
based on the checkbox and radio button selection
2.Also made changes to MongoDBDataSourcePageHelper.java to retain the
values of properties even wnhen they are not used but set in the UI.
Signed-off-by: Bharadwaj Tirunagaru <btirunag@opentext.com>

Mongo Db considering previous Connection details when we used MongoDB URI

---

pom.xml

Updated profile 'neon' with more current Tycho, MongoDB and Jetty versions.

Updating Jetty, MongoDB and Tycho versions in neon profile

---

engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/emitter/ContentEmitterAdapter.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/emitter/IContentEmitter.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/html/HTMLTableLayoutEmitter.java

Description of Issue: emitter with "multiple page" option disabled does not export content into single page due to hitting table cache limit
Description of Resolution: Add an emitter trigger function at the API layer.  Cache limit check is skipped when the emitter disables multiple sheet

Fixed emitter output to more than one page when hitting cache limit

---

engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/emitter/IContentEmitter.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/html/HTMLTableLayoutEmitter.java
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/ExcelEmitter.java

Revert the function addition at the IContentEmitter interface as there are other classes that implement this interface directly.  Keep the function at ContentEmitterAdapter and only check emitters that extend from this class

revert api change to prevent cascading effect

---

xtab/org.eclipse.birt.report.item.crosstab.core/src/org/eclipse/birt/report/item/crosstab/core/re/CrosstabQueryUtil.java

We found that at runtime, aggregate function count is getting converted to sum for crosstab queries for data model.

Cross tab using data model measure with aggregate function COUNT is automatically getting converted into SUM.

---

data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/api/querydefn/Binding.java
data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/impl/QueryExecutor.java

Made changes to consider script expression only for non aggregation bindings in sort and group expression handling in QueryExecutor.

Made changes to return correct arguments in Binding.

---

data/org.eclipse.birt.report.data.oda.jdbc/src/org/eclipse/birt/report/data/oda/jdbc/JDBCException.java
data/org.eclipse.birt.report.data.oda.jdbc/src/org/eclipse/birt/report/data/oda/jdbc/OdaJdbcDriver.java
data/org.eclipse.birt.report.data.oda.jdbc/src/org/eclipse/birt/report/data/oda/jdbc/utils/JDBCDriverInfoManager.java

1)Added an overloaded getmessage() to JDBCException  which now takes locale as an argument and displays the exception message in the locale
2)Also fixed a typo-error
Signed-off-by: Bharadwaj14 <tbharadwaj14@gmail.com>

Added an overloaded getmessage() to JDBCException

---

data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/impl/group/DecimalGroupCalculator.java

If the  value '-1',grouping interval doesn't work for negative categories .So I change the value to '-Double.MAX_VALUE'.

grouping interval doesn't work for negative categories.

---

UI/org.eclipse.birt.report.designer.ui.data/src/org/eclipse/birt/report/designer/data/ui/dataset/ResultSetPreviewPage.java

Root cause of the issue:
Regression caused by commits 0b411e2d, 6314f9b7, and 92ceae23
- There are 2 row fetch limit values for data set preview in BDPro. One is the data set preview display limit(default is 500), the other is data set source fetch limit(default is unlimited)
- Original intent of commits is to push down preview display limit(500) to ODA prepared statement when ODA data set fetch limit is default/ unlimited. This is to address accessing Big Data type of data source.
- This causes a regression where the 500 value is hardcoded and data set is always fetching at most 500 rows from data source. 
- The regression causes 2 issues:
1.Data set filters are always applied only on the fetched 500 rows of data rather than the entire data set
2.Customly setting the data source fetch …

fix regression bug on data set preview fetch row limit

---

core/org.eclipse.birt.core/src/org/eclipse/birt/core/data/DataTypeUtil.java

Rhino 1.7R4 onward library no longer gracefully handles string coercion. Older version of the library implicitly concatenates strings into a new String type where as in updated Rhino concatenated Strings are treated as ConsString type rather than String type.
Fix is to use the toString() provided by Rhino script to convert ConsString back to String type. 
Source code: https://github.com/mozilla/rhino/blob/master/src/org/mozilla/javascript/ConsString.java

fix String conversion due to updated Rhino script library

---

data/org.eclipse.birt.report.data.oda.jdbc.dbprofile.sampledb/src/org/eclipse/birt/report/data/oda/jdbc/dbprofile/sampledb/internal/impl/SampleDbFactory.java

There is an exception thrown on start of a workspace (birt-4.7/eclipse 4.7/windows 10/jdk8-64). 
---
java.io.FileNotFoundException: C:\src\ws\ws-debug-tbs-43\.metadata\.plugins\org.eclipse.birt.report.data.oda.jdbc.dbprofile.sampledb\db\META-INF\MANIFEST.MF (The system cannot find the path specified)
at java.io.FileOutputStream.open0(Native Method)
at java.io.FileOutputStream.open(Unknown Source)
at java.io.FileOutputStream.<init>(Unknown Source)
at java.io.FileOutputStream.<init>(Unknown Source)
at org.eclipse.birt.report.data.oda.jdbc.dbprofile.sampledb.internal.impl.SampleDbFactory.initSampleDb(SampleDbFactory.java:187)
at org.eclipse.birt.report.data.oda.jdbc.dbprofile.sampledb.internal.impl.SampleDbFactory.setInitializationData(SampleDbFactory.java:88)
Issue description:
=========== …

Fix FileNotFoundException thrown on workspace startup

---

data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/rank/NAccumulator.java
data/org.eclipse.birt.data.aggregation/src/org/eclipse/birt/data/aggregation/impl/rank/PercentAccumulator.java
data/org.eclipse.birt.data.tests/test/org/eclipse/birt/data/engine/binding/ComputedColumnTest.java
data/org.eclipse.birt.data.tests/test/org/eclipse/birt/data/engine/binding/golden/ComputedColumnTest.testTopNAggregationOnComputedColumnWithFilterOnEmptyDataSet.txt
data/org.eclipse.birt.data.tests/test/org/eclipse/birt/data/engine/binding/golden/ComputedColumnTest.testTopNPercentAggregationOnComputedColumnWithFilterOnEmptyDataSet.txt

For TopN/BottomN aggregation BIRT has a NAccumulator that contains a BasicCachedArray which stores all   running N elements. Aggregation is always assuming there is at least 1 element. So when all elements are filtered and aggregation is evaluated on empty input, the default N = -1 falls through to initialized size of BasicCachedArray. 
Add fix to properly evaluate the N value before passing it to initialize BasicCachedArray. The fix is similar for Top percent N aggregation.

add value check for N for N and Percent aggregation accumulator

---

viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/context/ViewerAttributeBean.java
viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/resource/Messages.properties
viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/resource/ResourceConstants.java
viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/viewer.properties

…d=538142
Through Birt Viewer, one can perform operations such as generating a report as a frameset, output the report document in some format, generate a report document and so on. One parameter these operations take is "__document" that represents the report document file to be generated. Using executable extension such as .jsp for the __document parameter and using a specially crafted report, one can access sensitive information about the system or do something nasty on the server by accessing the generated report document. The fix introduces a configurable whitelist and blacklist for the report document extension.

Fix for Security Issue : https://bugs.eclipse.org/bugs/show_bug.cgi?id=538142

---

viewer/org.eclipse.birt.report.viewer/jettyhome/etc/jetty.xml

upgraded jetty 9.3.9 uses GzipHandler to compress files, GZipFilter is deprecated

update jetty configuration to use GzipHandler

---

engine/org.eclipse.birt.report.engine.emitter.config.pdf/src/org/eclipse/birt/report/engine/emitter/config/pdf/PDFEmitterDescriptor.java
engine/org.eclipse.birt.report.engine.emitter.config.pdf/src/org/eclipse/birt/report/engine/emitter/config/pdf/i18n/messages.properties
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/IPDFRenderOption.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/impl/EngineTask.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/emitter/LayoutEngineContext.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/emitter/PDFLayoutEmitterProxy.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/emitter/TextAreaLayout.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/LayoutContext.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/LayoutEngine.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/TextCompositor.java

a condition is change to allow use of word break even when text area is not empty
also change code naming for better understanding

allow not empty text area to have word break, renaming and correcting pdf option hyphenation to word break

---

UI/org.eclipse.birt.report.designer.ui.data/META-INF/MANIFEST.MF
engine/uk.co.spudsoft.birt.emitters.excel.tests/META-INF/MANIFEST.MF
testsuites/org.eclipse.birt.report.tests.chart/META-INF/MANIFEST.MF

- removed non-existing 'library.jar's from classpath
- removed jars from classpath that are now imported from bundles
- added missing Automatic-Module-Name

Fixed warnings in MANIFESTs

---

features/org.eclipse.birt.engine.runtime/.project

Importing all BIRT eclipse projects fails because of a duplicate project name. This seems to be a copy-and-paste error.

Fixed duplicate project names

---

chart/org.eclipse.birt.chart.tests/META-INF/MANIFEST.MF
data/org.eclipse.birt.report.data.oda.jdbc.tests/META-INF/MANIFEST.MF

org.eclipse.birt.chart.tests and org.eclipse.birt.report.data.oda.jdbc.tests both use APIs from JavaSE-1.7 -> update RequiredExecutionEnvironment

Raised ReqExecEnv because of API use

---

chart/org.eclipse.birt.chart.engine/schema/aggregatefunctions.exsd
chart/org.eclipse.birt.chart.engine/schema/charttypes.exsd
chart/org.eclipse.birt.chart.engine/schema/datapointdefinitions.exsd
chart/org.eclipse.birt.chart.engine/schema/datasetprocessors.exsd
chart/org.eclipse.birt.chart.engine/schema/devicerenderers.exsd
chart/org.eclipse.birt.chart.engine/schema/displayservers.exsd
chart/org.eclipse.birt.chart.engine/schema/modelrenderers.exsd

Some of the extensions specified by BIRT itself did not match the extension point schema -> updated the schemas -> resolved warnings

Fixed plugin.xml warnings (missing unbounded in extension point schema)

---

BIRT_photon.target

I created a PDE target definition for the current target platform of the master branch. It resolves all dependencies currently needed by BIRT.
It is almost in sync with the tycho target platform. Only difference is the addition of a recent Apache Jasper version from Gemini as it is required by the Jetty Version currently used by BIRT.
Signed-off-by: Alexander Lehmann <a.lehm@gmx.de>

Add PDE target definition for Photon

---

pom.xml

revert datatool upgrade on oxygen for oxigen

datatool upgrade require eclipse to be photon or upper 

---

data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/impl/QueryExecutor.java

If we have filter and when we do preview results of DataSet filter,
filtering should be done on complete results
not just on the limited results obtained by limited max rows/ rowfetchlimit size.
Signed-off-by: Ravi Kiran Rimmanapudi <rrimmana@opentext.com>

In preview of dataset Filter is not applied on complete results but filtered on maxrows only.

---

data/org.eclipse.birt.report.data.oda.jdbc/src/org/eclipse/birt/report/data/oda/jdbc/Connection.java

This leaves no open transactions using the postgres driver the default way. As the postgres driver uses the policy DBConfig.SET_COMMIT_TO_FALSE configured in config.xml, which sets autocommit to false by default.
The open transaction was introduced by this commit: eclipse@3936b04
To show the "idle in transaction" open database connection (which is reused, though!) run
SELECT * FROM pg_stat_activity
on the database after generating a report using BIRT with PostgreSQL JNDI.
Signed-off-by: Bernhard Kiselka <bk@wigeogis.com>

commit before closing the connection

---

viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/utility/ParameterAccessor.java

Reflected XSS vulnerability in the __format URL parameter
It should also take care of the other parameters.
It make sure all parameter are escape to avoid attack.
tested with associate unit test.
Signed-off-by: shiheng guan <guans@opentext.com>

Fix for XSS vulnerability Bug 546816

---

.travis.yml
travis-maven-toolchain.xml

Travis has updated the default linux distribution from trusty to xenial. On xenial, OracleJDK 8 is not supported anymore. My solution: use OpenJDK 8 on xenial. Alternative solutions: use OracleJDK 8 on trusty or update to Oracle/OpenJDK 11 on xenial.

Fix Travis build

---

data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/impl/QueryResults.java

caused while running a report with chart that is based on Join DS from datadesign
Signed-off-by: Meeta Kapoor <mkapoor@opentext.com>

Fix to resolve the "Get page count failed" error 

---

engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLReportEmitter.java

X-Content-Type-Options: nosniff prevents the client browser from 'mime sniffing' but image does not display in IE

X-Content-Type-Options: nosniff prevents the client browser from 'mime sniffing' but image does not display in IE

---

model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/writer/ModuleWriterImpl.java

Avoid writing password into report design in case where Connection profile is used as data source

Avoid writing password into report design in case where Connection profile is used as data source

---

viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/utility/ParameterAccessor.java
viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/pages/common/Attributes.jsp

Redo fix to bug 456816 (CVE-2019-11776) to html-encode format parameter in the jsp rather than encoding all parameters which was causing problems in prepared queries.

Space is encoded in dataset parameter #623

---

engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/TableLayout.java

The commit https://github.com/eclipse/birt/commit/f84d0f812a72ba8e54f6caf641e16442d480594c caused severe issues.
In older releases of BIRT up to 4.6.0, the output was wrong (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=562873).
Newer releases (starting from 4.7.0) caused a NullPointerException when running the example report.
As a solution, removed the changes from that commit.

Bugfix for issue 636 - NPE with test report from eclipse bug 562873

---

engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/ExcelEmitter.java
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/HandlerState.java
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/FlattenedTableHandler.java
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/NestedTableHandler.java
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/PageHandler.java
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/TopLevelListHandler.java
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/TopLevelTableHandler.java
model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/util/BaseTestCase.java
viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/web.xml

Truncate sheet names that are too long and filter illegal sheet name characters.

XLSX tab naming can cause IllegalArgumentException #641

---

engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/PDFPageDevice.java

enable relative or universal paths by using context.getResource()
and do not print a "1 of 1" at the bottom of an added page by setting paginate = false for concatPDFs()
Reasoning: the prepended PDF is usually a cover page without pagination and the appended an annex also without a pagination
This relates to #439 and #567

Enable relative paths for PDF append and prepend

---

build/org.eclipse.birt.releng/BIRT.setup

Categorize the projects such that the more interesting projects, i.e., the actual bundles with source code, are easily identified and come first.
The result looks like this:
I wanted to understand the contribution process before working on https://github.com/eclipse/birt/issues/699

Improve the working sets of the Oomph setup

---

.project
UI/.project
build/.project
build/birt-packages/.project
build/birt-packages/birt-charts/.project
build/birt-packages/birt-nl/.project
chart/.project
common/.project
core/.project
data/.project
docs/.project
engine/.project
features/.project
model/.project
nl/.project
testsuites/.project
viewer/.project
xtab/.project

In general, for projects that contain nested projects, filter the
folders corresponding to such nested projects such that the nested
contents of those folders are not shown in the resource tree, although
the folder itself is shown.  Of course when the nested contents are not
in the resource tree, they are not shown in any explorers.
Note that this filtering is designed not to apply for folders starting
with a '.', e.g,. .settings folders.  These folders are hidden by
default in the explorers anyway but need must be present in order to
store project-specific preferences.

Add resource filters to parent projects #699

---

README.md

This ensures that all the projects will use a consistent image style for their buttons now and in the future should we want to make central style changes...
It looks like this:

Use the generated image for the development environment creation button

---

UI/org.eclipse.birt.report.designer.ui.views/src/org/eclipse/birt/report/designer/internal/ui/views/NonGEFSynchronizerWithTreeView.java
UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/editors/parts/TableCellKeyDelegate.java
UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/editors/schematic/tools/CellDragTracker.java

Changed to another "set selection strategy" since appending to a
existing selection yields a lot of selection changed events, which in
turn causes a lot of updates in other parts of BIRT.
Also, removed "reveal" of all the selected EditParts on the current
viewer. The logic behind this is that the user probably already sees the
EditParts which was selected. EditParts will still be revealed in other
places of BIRT.

UI performance degrades when selecting "many" cells in a grid/table #717

---

UI/org.eclipse.birt.report.designer.ui.editors.schematic/src/org/eclipse/birt/report/designer/internal/ui/editors/script/JSEditor.java

No longer generating fonts for this label, but using the FontRegistry to use JFace default fonts instead.

JSEditor is leaking fonts #734

---

build/org.eclipse.birt.target/BIRT all-in-one.launch
build/org.eclipse.birt.target/debug.options

This shows the resolver working during startup and allows us to find the cause for slow startup times

Add debug options to all-in-one launch config

---

chart/org.eclipse.birt.chart.device.pdf/META-INF/MANIFEST.MF

I was able to fix the resolution problems at startup (#757) with this change. Still need to investigate if this breaks anything.

Remove org.w3c.dom.events import from org.eclipse.birt.chart.device 

---

.github/workflows/ci.yml
chart/org.eclipse.birt.chart.tests/pom.xml

The chart tests did not run with the CI as they used to not work with maven, only when started from eclipse.

Enable chart tests in CI

---

engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/util/PPTXUtil.java

Null guard for when DimensionType.parseUnit() fails in
PPTXUtil.convertCssToEnum(). This happens typically when the
cssDimension is "auto" for margins, which really should have a special
case treatment in the TableWriter.endCell(). However, from the look of
it, the "margin" code in endCell needs a lot of refactoring and should
perhaps be done in other places in PPTXCanvas instead ( .drawText() etc
)

Defective PPTX format in BIRT #813

---

UI/org.eclipse.birt.report.designer.tests/build.properties
UI/org.eclipse.birt.report.designer.ui.preview.static_html/build.properties
UI/org.eclipse.birt.report.designer.ui.preview/build.properties
engine/org.eclipse.birt.report.engine.emitter.config/build.properties

This PR aims to remove the JavaSE-1.5 source level restriction still available on some projects which prevents PR #836 to build

Removed javacSource and javacTarget from build.properties files.

---

model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/api/golden/CompatibleExpression_golden.xml
model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/api/golden/CompatibleExpression_golden_1.xml
model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/api/golden/CompatibleExpression_golden_2.xml
model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/api/golden/DataCompatibleValueExpr_golden.xml
model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/parser/ParserCompatibilityTest.java
model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/parser/input/CompatibleConvertComputedColumnsConcatenateProperites.xml
model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/parser/IDesignSchemaConstants.java
model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/parser/OdaDataSetState.java
model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/util/VersionUtil.java

Added migration of old OdaDataSet that used translated strings
(Message.getString()), to the new property names introduced with commit
cac6e65a766ecbf1086728cebdbb5d54b4755728
I know that we are close to release, and introduce model migration for old issues may be a bad idea. - But here it is.

Some reports created with birt 4.2.1 don't work with 4.9.0 #838

---

chart/org.eclipse.birt.chart.ui.extension/src/org/eclipse/birt/chart/ui/swt/wizard/data/BaseDataDefinitionComponent.java
chart/org.eclipse.birt.chart.ui/src/org/eclipse/birt/chart/ui/integrate/ChartUIHelperBase.java

Enabled aggregation again. Seems to have been a negation wrong after refactoring. Also expanded
the default IChartUIHelper.useDataSetRow() implementation to a simple startsWith("data") check previously used in the enableAddEditor() method

Aggregation is disabled in charting #856

---

build/org.eclipse.birt.releng/BIRT.setup
build/org.eclipse.birt.target/org.eclipse.birt.target.target

Changing https://download.eclipse.org/eclipse/updates/4.24-I-builds/ for
now.

Master is not building due to broken target platform #869

---

data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/impl/QueryResults.java

IServiceForQueryResults.close() is now closed upon QueryResults.close(). This is currently the only place in the frame work were IServiceForQueryResults.close() is called.
@hvbtup : Since you have problems with your dev.environment I took the liberty to make a PR for you to test.

Report with Oracle JDBC ORA-01000 Too many open cursors #875

---

build/org.eclipse.birt.target/org.eclipse.birt.target.target

Switching to the https://download.eclipse.org/eclipse/updates/4.23/
update-site

Master is not building due to broken target platform, (Again) #877

---

engine/org.eclipse.birt.report.engine.emitter.postscript/src/org/eclipse/birt/report/engine/emitter/postscript/PostscriptWriter.java

During reflective access to the "trueTypeFonts" field of
"FontFactoryImpl" the type "Properties" was assumed, but the type has
changed to "HashMap" in OpenPDF. Stopped using reflective access to the
field since there are now API to access the content of "trueTypeFonts".

ClassCastException while emitting "postscript" format #1010

---

viewer/org.eclipse.birt.report.viewer.tests/test/org/eclipse/birt/report/context/ViewerAttributeBeanTest.java
viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/context/ViewerAttributeBean.java

Fixes an exploit in the BIRT viewer to block file extensions with special characters.

Bug 580994 - BIRT 4.10.0-20221001 - CVE-2021-34427 fix bypass

---

data/org.eclipse.birt.report.data.oda.jdbc/src/org/eclipse/birt/report/data/oda/jdbc/Connection.java

In the case that maxStatements = 0 and maxConnections is not 0, but a finite number (e.g. 32767 in SQL Server). Then this code previously would return 1. This makes BIRT generate thousands of connections for many of our reports. This is unacceptably slow. We change the code to return 0 (=unlimited) when maxStatements=0 after this change, regardless of the number of max connections. This will in most cases have BIRT use only one connection.
In general, the code should reflect that creating Connections is expensive in most contexts.

Adjust getMaxQueries to return correct number

---

chart/org.eclipse.birt.chart.engine/src/org/eclipse/birt/chart/factory/Generator.java

Scale resizing was done on every render leading to ever thicker lines when resizing. Now scale resizing is done once per render session.

Thick lines on chart after repeated build/render #1121

---

viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/utility/ParameterAccessor.java
viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/web-template.xml
viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/web-viewer.xml
viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/web-war.xml
viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/web.xml
viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/web_deploy.xml

Hardened the capability of running reports with an absolute file path.

Fix report path vulnerability #1164

---

engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/CellContentHandler.java

The enhancement make the option of data url accessible for excel output which is located into text element based on image tag.

Added image data URL handling to the excel cell content handler (#1237)

---

engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLReportEmitter.java

BIRT-preview root-tag not correct initialized, part of the root attributes will be displayed at the top of each report #1304

BIRT-preview root-tag not correct initialized #1304

---

build/birt-packages/birt-runtime-osgi/reportengine.product

This ensures, for one thing, that javax.xml.soap is available.
https://github.com/eclipse-birt/birt/issues/1340

Include org.eclipse.birt.chart.osgi.runtime in birt-runtime-osgi

---

build/birt-packages/birt-runtime-osgi/build.xml

https://github.com/eclipse-birt/birt/issues/1340

For birt-runtime-osgi copy javax.xml.soap jar to the lib folder

---

build/birt-packages/birt-runtime-osgi/build.xml

I.e., jakarta.xml.bind, org.apache.commons.logging, and org.apache.commons.discovery/*.jar
https://github.com/eclipse-birt/birt/issues/1340

Copy more content into the lib folder of birt-runtime-osgi

---

data/org.eclipse.birt.report.data.oda.jdbc/src/org/eclipse/birt/report/data/oda/jdbc/Statement.java

Fix prepared statement setNull() #1365

Fix prepared statement setNull() #1365

---

data/org.eclipse.birt.report.data.oda.jdbc/src/org/eclipse/birt/report/data/oda/jdbc/Statement.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/LineArea.java

Fix align issue of "inline" elements (#1372)

Fix align issue of "inline" elements (#1372)

---

engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLReportEmitter.java

Fix issue of NullPointerException on html-img-tag based on data-URL (#1382)

Fix issue of NullPointerException on html-img-tag based on data-URL

---

UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/core/model/schematic/ImageHandleAdapter.java
UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/util/ImageManager.java
engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLReportEmitter.java
engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/AbstractEmitterImpl.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/emitter/EmitterUtil.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/emitter/ImageReader.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/presentation/LocalizedContentVisitor.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/util/SvgFile.java
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/CellContentHandler.java

enhancement to improve the svg-image-handling and the usage of data-url #1386

Enhancement to improve the svg-image-handling and the usage of data-url #1386

---

UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/core/model/schematic/ImageHandleAdapter.java
UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/util/DEUtil.java
UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/util/ImageManager.java
chart/org.eclipse.birt.chart.reportitem.ui/src/org/eclipse/birt/chart/reportitem/ui/ReportDataServiceProvider.java
engine/org.eclipse.birt.report.engine.emitter.config.docx/src/org/eclipse/birt/report/engine/emitter/config/docx/DocxEmitterDescriptor.java
engine/org.eclipse.birt.report.engine.emitter.config/src/org/eclipse/birt/report/engine/emitter/config/ConfigurableOption.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/DocxRenderOption.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/impl/Image.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/emitter/ImageReader.java
model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/AbstractThemeHandle.java
model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/ReportItemHandleImpl.java
model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/elements/interfaces/IInternalReportItemModel.java

Fix eclipse warnings of missing comments and usage of raw types

Fix eclipse warnings of missing comments and usage of raw types (#1386)

---

UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/core/model/schematic/ImageHandleAdapter.java
UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/util/DEUtil.java
UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/editors/schematic/editparts/ImageEditPart.java
UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/editors/schematic/figures/ImageFigure.java
UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/layout/ReportFlowLayout.java
engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLPerformanceOptimize.java
engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLReportEmitter.java
engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/AbstractEmitterImpl.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/HTMLServerImageHandler.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/IImage.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/ImageSize.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/impl/Image.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/content/IImageContent.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/content/impl/ImageContent.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/internal/content/wrap/ImageContent.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/ImageAreaLayout.java
model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/DimensionHandle.java

Images with dimension unit percentage should be sized on the original image size (raster images: px of width and height) (#1401)

Images with dimension unit percentage should be sized on the original  (#1401)

---

UI/org.eclipse.birt.report.designer.ui.rcp/BIRT-headless.product
UI/org.eclipse.birt.report.designer.ui.rcp/BIRT.product
build/birt-packages/birt-report-all-in-one/BIRT.product
build/birt-packages/birt-report-rcp/BIRT.product
build/org.eclipse.birt.releng/BIRT.setup
build/org.eclipse.birt.target/org.eclipse.birt.target.target
common/org.apache.batik.transcoder.birt.ext/META-INF/MANIFEST.MF
engine/uk.co.spudsoft.birt.emitters.excel/META-INF/MANIFEST.MF

THe products are over-specified and include directly things that are also indirectly induced by other things.  In this case, the Platform's evolving use of ECF is causing a problem.
https://github.com/eclipse-birt/birt/pull/1433

Remove ECF from products

---

engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLReportEmitter.java

Fix of images which are embedded like URL on an html document which is embedded into a birt report element (e.g. dynamic text)

Fix of images handling of HTML embedded images which cause NullPointerException (#1436)

---

engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/AreaFactory.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/BlockContainerArea.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/ContainerArea.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/LineArea.java

Fix area line margin-top of first line after page break (#1443)

Fix area line margin-top of first line after page break (#1443)

---

common/org.apache.axis/META-INF/MANIFEST.MF

Added missing Import-Package: headers to "our" version of Axis 1.4.1
I do not know the state of the Axis in Orbit. It has the correct import statements but I do not know if it contains the fixes for the vulnerabilities mentioned in #662, which made us build our own version of Axis.

java.lang.NoClassDefFoundError when starting WebViewer #1451

---

promotion/pom.xml

Product archives for Linux and Mac have changed from zip files to tar.gz files. Currently org.eclipse.birt.promote fails since it still uses .zip for these files.

org.eclipse.birt.promote fails on master builds #1470

---

engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/AbstractRealTableCellHandler.java
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/AbstractRealTableRowHandler.java

Fix the excel-issue if an blank row with merged cells will be removed then remove the registered merge area from the excel-sheet and also an additional double check is added to avoid overlapping merge registrations on the excel-sheet (#1455)

Fix excel-issue of removed row then remove also regsitered merge regions from sheet (#1455)

---

UI/org.eclipse.birt.report.designer.ui.rcp/BIRT-headless.product
UI/org.eclipse.birt.report.designer.ui.rcp/BIRT.product
build/org.eclipse.birt.releng/BIRT.setup
build/org.eclipse.birt.target/org.eclipse.birt.target.target

Also remove unnecessary includes of lucene from products to help induce a more stable generated target platform.
https://github.com/eclipse-birt/birt/issues/1474

Improve the setup to generate a correct target platform

---

chart/org.eclipse.birt.chart.ui.extension/src/org/eclipse/birt/chart/ui/swt/composites/FillChooserComposite.java
chart/org.eclipse.birt.chart.ui.extension/src/org/eclipse/birt/chart/ui/swt/composites/FontCanvas.java
chart/org.eclipse.birt.chart.ui.extension/src/org/eclipse/birt/chart/ui/swt/composites/FontDefinitionComposite.java
chart/org.eclipse.birt.chart.ui.extension/src/org/eclipse/birt/chart/ui/swt/composites/IntegerSpinControl.java
core/org.eclipse.birt.core.ui/src/org/eclipse/birt/core/ui/frameworks/taskwizard/composites/MessageComposite.java
core/org.eclipse.birt.core.ui/src/org/eclipse/birt/core/ui/swt/custom/CustomChooserComposite.java
core/org.eclipse.birt.core.ui/src/org/eclipse/birt/core/ui/swt/custom/TextCombo.java

Long since, when I just wanted to do a small fix for #840 I ended up doing some substantial changes to some custom UI controls, since they typically didn't work well on Linux and probably not on any system where the font differs from Windows default, incl UI scaling.
This PR addresses them as well as some other resource leaks.
**TextCombo layout used on "Script tab"**
Before
After
**Chart style selectors**
Before
After
**Font selector**
Before
After

Fixes some UI strangeness in Birt Designer

---

engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/font/FontMappingConfig.java

Fix the font alias name to lower case handling (#1385)

Fix the font alias name to lower case handling (#1385)

---

nl/org.eclipse.birt.report.viewer.nl/src/org/eclipse/birt/report/resource/.gitignore
viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/resource/Messages.properties
viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/ajax/ui/dialog/BirtExportReportDialog.js
viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/ajax/utility/Constants.js
viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/pages/dialog/ExportReportDialogFragment.jsp

This is an enhancement to add the option to create a single sheet output directly with the viewer export based on the Spudsoft option  (#645)
The option will be displayed if the Spudsoft XLS or XLSX is selected.

Enhance of the export viewer dialog to add the excel single sheet option (#645)

---

build/org.eclipse.birt.target/org.eclipse.birt.target.target

This also fixes the strange java.xml.namespace.QName compile error though why that's the case isn't clear.
https://github.com/eclipse-birt/birt/issues/1492

Regenerate the target platform after DataTools changes

---

build/org.eclipse.birt.target/org.eclipse.birt.target.target
pom.xml

Upgrade Tycho to 4.0.4.
https://github.com/eclipse-birt/birt/issues/1508

Regenerate the target platform for Eclipse 4.31

---

engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/util/SvgFile.java

The method isSvg(String) needs additional brackets to avoid a possible NullPointerException.

Fix the issue with null-reference of uri in SvgFile.isSvg() (#1525)

---

engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/ExcelEmitter.java

dispose of temporary files backing this workbook on disk after writing into output stream

dispose of temp-files when using StreamingXlsx in XlsxEmitter #1533

---

engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/LineArea.java

This fixes #1536. Note that preserving leading whitespace only works for data items, but not for dynamic text items.

Fix data item leading whitespace preserve #1536

---

build/org.eclipse.birt.releng/BIRT.setup
build/org.eclipse.birt.target/org.eclipse.birt.target.target
features/org.eclipse.birt.feature/feature.xml

Eliminate org.eclipse.jetty.servlet from the org.eclipse.birt feature.

Simplify the repositories used for the target platform

---

UI/org.eclipse.birt.report.debug.core/.classpath
UI/org.eclipse.birt.report.designer.ui.rcp/BIRT-headless.product
UI/org.eclipse.birt.report.designer.ui.rcp/BIRT.product
build/birt-packages/birt-runtime-osgi/pom.xml
build/org.eclipse.birt.api/build.xml
build/org.eclipse.birt.releng.birtbuilder/eclipse/buildConfigs/birt/tools/BIRTDownloadSetup.xml
build/org.eclipse.birt.sdk/pom.xml
build/org.eclipse.birt.target/org.eclipse.birt.target.target
chart/org.eclipse.birt.chart.viewer/BuildChartWebViewer.xml
core/org.eclipse.birt.core/META-INF/MANIFEST.MF
docs/org.eclipse.birt.chart.doc.isv/BuildChartISVDoc.xml
docs/org.eclipse.birt.doc.isv/BuildISVDoc.xml
features/org.eclipse.birt.chart.feature/feature.xml
features/org.eclipse.birt.chart.osgi.runtime/feature.xml
features/org.eclipse.birt.engine.runtime/feature.xml
features/org.eclipse.birt.feature/feature.xml
features/org.eclipse.birt.osgi.runtime/feature.xml
features/org.eclipse.birt.report.designer.editor.xml.wtp.feature/feature.xml
pom.xml
promotion/pom.xml
viewer/org.eclipse.birt.report.viewer/WebViewerPackager.xml
viewer/org.eclipse.birt.report.viewer/customBuildCallbacks.xml

https://github.com/eclipse-birt/birt/issues/1566

Use org.mozilla.rhino instead of org.mozilla.javascript

---

UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/palette/BasePaletteFactory.java
UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/palette/DesignerPaletteFactory.java
build/org.eclipse.birt.releng/BIRT.setup
build/org.eclipse.birt.target/org.eclipse.birt.target.target

Update the setup for generating this target platform, but also easily configured to switch back to on-going development versions.
Fix compile problems compiling against the latest GEF release.
https://github.com/eclipse-birt/birt/issues/1572

Lock the target platform onto stable update sites

---

UI/org.eclipse.birt.report.designer.ui.rcp/BIRT-headless.product
UI/org.eclipse.birt.report.designer.ui.rcp/BIRT.product
features/org.eclipse.birt.feature/feature.xml

The preview tab cannot work without the contribution from bundle org.eclipse.birt.report.designer.ui.preview.static_html so that bundle should be included in features and products that include org.eclipse.birt.report.designer.ui.preview.
https://github.com/eclipse-birt/birt/issues/1589

ReportPreviewFormPage needs StaticHTMLViewer

---

engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/HTMLServerImageHandler.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/util/FileUtil.java

fix issue with embedded svg images added like data-URL (#1604)

fix issue with embedded svg images added like data-URL (#1604)

---

viewer/org.eclipse.birt.report.viewer/src/org/eclipse/birt/report/viewer/utilities/ViewerWebServer.java

Fix the issue with spaces into the designer path on "viewer web server" side (part 02, #1621)
- PR #1621 solved the issue on "ViewerWebApp.start()"
The current nightly build shows that now an additional issue is on "ViewerWebServer" with the same problem
and this PR should solve the issue.
Error message:

Fix the issue with spaces into the designer path on "viewer web server" side (part 02, #1621)

---

engine/org.eclipse.birt.report.engine.emitter.docx/src/org/eclipse/birt/report/engine/emitter/docx/writer/Document.java
engine/org.eclipse.birt.report.engine.emitter.docx/src/org/eclipse/birt/report/engine/emitter/docx/writer/DocxWriter.java
engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/AbstractEmitterImpl.java
engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/DocEmitter.java
engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/IWordWriter.java
engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/writer/DocWriter.java

Enhancement to add the document language to DOCX based on the report locale (#1620)

Enhancement to add the document language to DOCX based on the report locale (#1620)

---

data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/executor/DataSourceQuery.java
data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/impl/CancelManager.java

Switch from List to Map on CancelManager to improve performance, 
Fix memory leak & reduce scope of synchronized block Issue #1633

Fix memory leak & and use Map instead of list to avoid itterating an Array constantly inside a synchronized block

---

engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/ExcelEmitter.java
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/README.md
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/StyleManagerUtils.java
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/CellContentHandler.java

Enhancement to add excel formula options (#1643)

Enhancement to add excel formula options (#1643)

---

engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/BirtStyle.java
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/ClientAnchorConversions.java
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/ExcelEmitter.java
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/README.md
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/StyleManager.java
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/StyleManagerUtils.java
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/CellContentHandler.java

Enhance the excel output to get the formatting option of text-indent (#1666)

Enhance the excel output to get the formatting option of text-indent (#1666)

---

engine/org.eclipse.birt.report.engine.emitter.postscript/src/org/eclipse/birt/report/engine/emitter/postscript/header.ps

Fix the structure of "drawstreamimage" on "header.ps"-file by edding an "end" (#1669)

Fix the structure of "drawstreamimage" on "header.ps"-file by edding an "end" (#1669)

---

UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/editors/rulers/EditorRulerLayout.java
UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/editors/schematic/editparts/TableEditPart.java
UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/editors/schematic/editpolicies/TableXYLayoutEditPolicy.java
UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/layout/TableLayout.java

Fix BIRT-designer, switch from XYLayout to AbstractConstraintLayout and switch from XYLayoutEditPolicy to ConstrainedLayoutEditPolicy (#1665)

Fix BIRT-designer, replaced XYLayout and XYLayoutEditPolicy (#1665)

---

UI/org.eclipse.birt.report.designer.ui/META-INF/MANIFEST.MF
UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/script/ScriptValidator.java
data/org.eclipse.birt.report.engine.script.javascript/src/org/eclipse/birt/report/engine/javascript/JavascriptEngine.java
data/org.eclipse.birt.report.engine.script.javascript/src/org/eclipse/birt/report/engine/javascript/JavascriptVersion.java
data/org.eclipse.birt.report.engine.script.javascript/src/org/eclipse/birt/report/engine/javascript/README.md
model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/parser/IDesignSchemaConstants.java
model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/util/VersionUtil.java

Enhancement to add ECMAScript 6 support (#1574)

Enhancement to add ECMAScript 6 support (#1574)

---

UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/script/JSPartitionScanner.java

The members of objects will be highlighted too.

Enhance syntax highlights for object members (#1684)

---

UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/dialogs/FormatNumberLayoutPeer.java
UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/ui/dialogs/CascadingParametersDialog.java
UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/ui/dialogs/ParameterDialog.java
core/org.eclipse.birt.core/src/org/eclipse/birt/core/format/NumberFormatter.java
engine/org.eclipse.birt.report.engine.dataextraction.csv.tests/test/org/eclipse/birt/report/engine/dataextraction/csv/testDataTypesLocalized.csv
engine/org.eclipse.birt.report.engine.dataextraction.csv/src/org/eclipse/birt/report/engine/dataextraction/csv/CSVDataExtractionImpl.java
engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLEmitter.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/value/FloatValue.java
model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/metadata/FloatPropertyType.java
model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/util/DimensionValueUtil.java
testsuites/org.eclipse.birt.report.tests.model/src/org/eclipse/birt/report/tests/model/api/GroupHandleTest.java
testsuites/org.eclipse.birt.report.tests.model/src/org/eclipse/birt/report/tests/model/regression/Regression_102725.java

Changed from the standard java number format classes to "com.ibm.icu.text"
and increase the preview values for the designer:
Old:
DEFAULT_PREVIEW_NUMBER = 1234.56;
DEFAULT_PREVIEW_INTEGER = 123456;
New:
DEFAULT_PREVIEW_NUMBER = 123456.78;
DEFAULT_PREVIEW_INTEGER = 12345678;

Fix number format for "lakhs" format based on com.ibm.icu.text.* (#1672)

---

build/birt-packages/birt-report-all-in-one/BIRT.product
chart/org.eclipse.birt.chart.ui/src/org/eclipse/birt/chart/ui/util/ChartUIUtil.java

1. Sometimes NumberFormat is used to handle the decimal point
and in other cases there is a dependency on ULocale.
A small fix was made to use the default ULocale in the
Numberformat calculations instead of the default NumberFormat
The whole operation is not fully understood so more issues
could arise.
2. To avoid memory cramps, an additional 1GB was added to the
maximum memory.
See the issue for a discussion.

Out of memory error when creating a chart #1727

---

engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/CellContentHandler.java

The scaling of the images will be done based on the given dimension if one of dimesnions are missing in relation to the given physical deimensions.

Fix the image scaling based on the given dimension (#1750)

---

engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/ExcelEmitter.java
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/README.md
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/PageHandler.java

The image scaling is enhanced to keep the original image size of small images without scaling to cell dimension

Enhance the image scaling of excel and keep the size of small images (#1752)

---

engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/CellImage.java
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/CellContentHandler.java
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/PageHandler.java

This enhancement enable the image alignment for excel output

Enhance the image alignment for excel (#1760)

---

UI/org.eclipse.birt.report.designer.core/META-INF/MANIFEST.MF
build/birt-packages/birt-report-all-in-one/BIRT.product
build/birt-packages/birt-runtime-osgi/reportengine.product
build/org.eclipse.birt.target/org.eclipse.birt.target.target
engine/org.eclipse.birt.report.engine/META-INF/MANIFEST.MF
features/org.eclipse.birt.chart.doc.isv.feature/feature.xml
features/org.eclipse.birt.chart.feature/feature.xml
features/org.eclipse.birt.chart.integration.wtp.feature/feature.xml
features/org.eclipse.birt.chart.osgi.runtime/feature.xml
features/org.eclipse.birt.cshelp.feature/feature.xml
features/org.eclipse.birt.doc.feature/feature.xml
features/org.eclipse.birt.doc.isv.feature/feature.xml
features/org.eclipse.birt.engine.runtime/feature.xml
features/org.eclipse.birt.example.feature/feature.xml
features/org.eclipse.birt.feature/feature.xml
features/org.eclipse.birt.integration.wtp.feature/feature.xml
features/org.eclipse.birt.osgi.runtime/feature.xml
features/org.eclipse.birt.report.designer.editor.xml.wtp.feature/feature.xml
pom.xml

- Use jgit timestamp provider for product qualifiers.
- Add org.apache.batik.ext.awt.image.codec.imageio where org.apache.batik.transcoder.image is used.
- Reduce the content of the all-in-one product, mostly to remove redundant includes.
- Ensure the runtime product is complete enough after the features have been simplified such tha the OSGi runtime test still works.

Remove references to non-BIRT bundles from features

---

engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/util/TableProcessor.java
engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/ExcelEmitter.java
model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/DesignElementHandle.java
model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/ErrorDetail.java
model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/api/ReportDesignHandleImpl.java

The PR includes some changes to reduce the java warnings based on optimization of:
- java documentation
- use raw types with type operator
- replace deprecated methods

Enhance comments, raw types and other small hints to reduce java warnings

---

build/birt-packages/birt-runtime-osgi/reportengine.product
features/org.eclipse.birt.chart.osgi.runtime/feature.xml
viewer/org.eclipse.birt.report.viewer/META-INF/MANIFEST.MF

- Remove org.eclipse.rcp to eliminate UI dependencies.
- Add a minimized set of additional plugins.
- Remove UI bundles from the org.eclipse.birt.chart.osgi.runtime feature.
- Remove org.eclipse.core.resources from org.eclipse.birt.report.viewer.

Reduce org.eclipse.birt.engine.runtime content

---

xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/internal/ui/editors/editparts/CrosstabTableEditPart.java
xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/internal/ui/editors/editpolicies/CrosstabXYLayoutEditPolicy.java

https://github.com/eclipse-birt/birt/issues/1824

Switch CrosstabXYLayoutEditPolicy to use TableXYLayoutEditPolicy

---

build/org.eclipse.birt.releng/BIRT.setup
build/org.eclipse.birt.target/org.eclipse.birt.target.target
chart/org.eclipse.birt.chart.tests/META-INF/MANIFEST.MF
chart/org.eclipse.birt.chart.tests/src/org/eclipse/birt/chart/tests/device/render/ImageOutputBaseTest.java
testsuites/org.eclipse.birt.report.tests.chart/META-INF/MANIFEST.MF
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/ChartTestCase.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_101855.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_115433.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_131308.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_133237.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_134309.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_134885.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_137166.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_142689.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_155185.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_76910.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_76963.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_98257.java

- Disable tests that fail with the new target platform for later investigation.
https://github.com/eclipse-birt/birt/issues/1828

Update the target platform to use the new version of derby

---

data/org.eclipse.birt.report.data.oda.jdbc/src/org/eclipse/birt/report/data/oda/jdbc/JDBCDriverManager.java

Enhance the JDBC Driver Manager to validate all driver supported properties and remove the unsupported from the connection properties, e.g. not all drivers support Bidi-properties according to DuckDB (JDBC-driver, #1825)

Enhance the JDBC Driver Manager to validate all driver supported properies (JDBC-driver, #1825)

---

chart/org.eclipse.birt.chart.tests/pom.xml
core/org.eclipse.birt.core.testhelper/META-INF/MANIFEST.MF
core/org.eclipse.birt.core.tests/META-INF/MANIFEST.MF
core/org.eclipse.birt.core.tests/pom.xml
data/org.eclipse.birt.report.data.adapter/META-INF/MANIFEST.MF
data/org.eclipse.birt.report.data.oda.xml/META-INF/MANIFEST.MF
engine/org.eclipse.birt.report.engine.dataextraction.csv.tests/META-INF/MANIFEST.MF
engine/org.eclipse.birt.report.engine.emitter.pdf.tests/pom.xml
engine/org.eclipse.birt.report.engine.emitter.postscript.tests/META-INF/MANIFEST.MF
engine/uk.co.spudsoft.birt.emitters.excel.tests/pom.xml
features/org.eclipse.birt.osgi.runtime/feature.xml
model/org.eclipse.birt.report.model.adapter.oda.tests/META-INF/MANIFEST.MF
model/org.eclipse.birt.report.model.tests/pom.xml
testsuites/org.eclipse.birt.report.tests.chart/META-INF/MANIFEST.MF
testsuites/org.eclipse.birt.report.tests.chart/pom.xml
testsuites/org.eclipse.birt.report.tests.engine/META-INF/MANIFEST.MF
testsuites/org.eclipse.birt.report.tests.model/META-INF/MANIFEST.MF
testsuites/org.eclipse.birt.tests.data/META-INF/MANIFEST.MF
viewer/org.eclipse.birt.report.viewer.tests/META-INF/MANIFEST.MF
xtab/org.eclipse.birt.report.item.crosstab.core.tests/META-INF/MANIFEST.MF
xtab/org.eclipse.birt.report.item.crosstab.core.tests/pom.xml

- Remove org.eclipse.birt.report.viewer and org.eclipse.birt.data.oda.mongodb.ui from org.eclipse.birt.osgi.runtime
feature.
- Simplify test dependency configuration.
- The org.junit dependencies aren't optional and non-test bundles should not have such a dependency, even an optional one.

Remove UI dependencies from org.eclipse.birt.osgi.runtime

---

features/org.eclipse.birt.engine.runtime/feature.xml

- Also add org.eclipse.birt.chart.device.pdf which the only plugin included by org.eclipse.birt.chart.osgi.runtime but not by org.eclipse.birt.engine.runtime.

Ensure that org.apache.axis is in the org.eclipse.birt.engine.runtime

---

build/org.eclipse.birt.target/BIRT Chart Test.launch
build/org.eclipse.birt.target/BIRT Report Tests Chart Test.launch
chart/org.eclipse.birt.chart.tests/src/org/eclipse/birt/chart/tests/device/render/ImageOutputBaseTest.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_101855.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_131308.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_133237.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_134309.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_134885.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_137166.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_142689.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_155185.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_76910.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_76963.java
testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_98257.java
testsuites/org.eclipse.birt.tests.core/src/utility/ImageUtil.java

- Support the `system property birt.rendering.tests.enabled` set to `true` to enable the tests even on Windows and enable it in the IDE launchers where the tests function correctly.
https://github.com/eclipse-birt/birt/issues/1828

Only disable the failing rendering tests for windows

---

build/birt-packages/birt-charts/DeploymentRuntime/category.xml
build/birt-packages/birt-runtime-osgi/build.xml
build/org.eclipse.birt.releng/BIRT.setup
build/org.eclipse.birt.target/org.eclipse.birt.target.target
data/org.eclipse.birt.report.data.oda.excel/META-INF/MANIFEST.MF
engine/uk.co.spudsoft.birt.emitters.excel/META-INF/MANIFEST.MF

- Add a dependency to org.apache.logging.log4j.to.slf4j so that org.apache.logging.log4j.api finds a Provider.
- Avoid direct dependencies on org.apache.commons.commons-logging because it's been a source of incompatibility problems in SimRel.
- Update webtools site to use content that's going into SimRel 2024-09.

Fix deadlock when POI tried to initialize its logger

---

build/birt-packages/birt-runtime-test/src/test/java/org/eclipse/birt/sdk/BaseTestTemplate.java
build/birt-packages/birt-runtime-test/src/test/java/org/eclipse/birt/sdk/RuntimeOSGiTest.java
build/birt-packages/birt-runtime-test/src/test/java/org/eclipse/birt/sdk/RuntimeTest.java
features/org.eclipse.birt.engine.runtime/feature.xml
features/org.eclipse.birt.osgi.runtime/feature.xml
viewer/org.eclipse.birt.report.viewer.tests/test/org/eclipse/birt/report/viewer/utility/AxisEncodingTest.java

- Include org.eclipse.birt.axis.overlay in the org.eclipse.birt.engine.runtime feature.
- Test both runtimes that they use the overlay correctly.
- Reconcile the difference between the features org.eclipse.birt.osgi.runtime and org.eclipse.birt.engine.runtime.
- Remove org.eclipse.birt.resources because it only provides cheatsheet content for in the IDE.
- Add org.eclipse.birt.chart.device.pdf and org.eclipse.birt.report.engine.emitter.prototype.excel.

Test org.eclipse.birt.axis.utility.UTF8Encoder is used and is correct

---

build/birt-packages/birt-runtime-osgi/reportengine.product

- Include only the org.eclipse.birt.osgi.runtime feature.

Simplify the org.eclipse.birt.engine.runtime product

---

build/birt-packages/birt-report-all-in-one/BIRT.product
build/org.eclipse.birt.p2updatesite/category.xml

- This allows an all-in-one product installation to be provisioned purely from the BIRT update site.
- With that possibility, Oomph can generate a product definition for use in the installer just like it does for the EPP products and the Platform's SDK product.

Enhance the update site to include all all-in-one product features

---

UI/org.eclipse.birt.report.designer.ui.preview.static_html/src/org/eclipse/birt/report/designer/ui/viewer/StaticHTMLViewer.java
UI/org.eclipse.birt.report.designer.ui.preview/plugin.properties
UI/org.eclipse.birt.report.designer.ui.preview/src/org/eclipse/birt/report/designer/ui/preview/editors/ReportPreviewFormPage.java

After switching the default browser to Edge in issues #1736 and #1737 the preview pane was broken because Edge does not like plain filenames.
Fixed:
1. Convert the plain file name to a file URL
This also fixed:
* Ask to save the editor when it is dirty and Preview is requested. #1902
* 'New Preview Prototype' tab must be called Preview #1903

The preview does not work anymore: #1901

---

engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXCanvas.java
engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TextWriter.java

The hyperlink undecoration won't be supported through PPTX because the PresentationML doesn't defined an option to avoid hyperlink decoration. The undecoration of a hyperlink will remove the the hyperlink on PPTX.

Fix the correct PPTX handling of hyperlink decoration

---

engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/TextAreaLayout.java

This replaces TAB characters with spaces when Data items contain TAB control characters, by replacing the TABs with spaces in the `transform` method.

Fix PDF/A conformance when data item contains TAB character

---

build/org.eclipse.birt.releng/BIRT.setup
build/org.eclipse.birt.target/org.eclipse.birt.target.target

- The setup change is temporary until 4.19 development begins.
- Similarly the target platform will be regenerated to moving-target sites when 4.19 begins.
- Only the datatools site is still a moving target pending a 1.16.2 release.
https://github.com/eclipse-birt/birt/issues/1910

Update the setup and the target platform specify permanent sites

---

build/birt-packages/birt-runtime-osgi/build.xml

The logging factory is switched from "org.apache.commons.logging" to "org.apache.commons.commons-logging" and must be copied from platform/plugins-folder to the WEB-INF/lib-folder.

BIRT OSGi, copy org.apache.commons.commons-logging to the lib-folder

---

UI/org.eclipse.birt.report.designer.samplereports/samplereports/Reporting Feature Examples/PDF Vertical Tab/.project
UI/org.eclipse.birt.report.designer.samplereports/samplereports/Reporting Feature Examples/PDF Vertical Tab/vertical_tab_1.rptdesign
UI/org.eclipse.birt.report.designer.samplereports/samplereports/Reporting Feature Examples/PDF Vertical Tab/vertical_tab_2.rptdesign
UI/org.eclipse.birt.report.designer.samplereports/samplereports/Reporting Feature Examples/PDF Vertical Tab/vertical_tab_3.rptdesign
UI/org.eclipse.birt.report.designer.samplereports/samplereports/Reporting Feature Examples/PDF Vertical Tab/vertical_tab_4.rptdesign
engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/README.md
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/BlockContainerArea.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/ContainerArea.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/RowArea.java

This adds two user properties which can be used in Cell or in Text/Label items to achieve a functionality like a vertical tab stop.
Example reports for both properties are provided, which two different values "10cm" and "20cm" which show the effect.
For "10cm", the current y position already is more than 10cm from the top, so there is no effect. For "20cm", the current y position is less than 20cm from the top, so the effect is to go down until 20cm from the top.
"top" means the start of the body, eg. when the master page has 1cm margin-top and 1cm header height, it is 22cm from the top of the sheet.
The property is useful in some special use cases, which are not frequent enought to justify the introduction of an additional property to the ROM. That's why I think that user properties are …

PDF emitter VerticalTab user property

---

engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/AbstractEmitterImpl.java
engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/writer/AbstractWordXmlWriter.java

The optimization is for DOCX and the new option of header/footer without layout grid.
For this option the positions of the header and footer will be re-calculated.
The 2 methods `writeSectionInBody()` and `writeSectionInPara()` will use the same logic to handle the header and footer calculation.
The original behavor can be reconfigured very simple with the property register "Advanced" at the property editor on report-level. If the word-option "Use layot grid of header & footer" then the old behavior will be used.

DOCX, optimize header & footer handling (#2026)

---

engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/LineArea.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/TextArea.java
engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/TextCompositor.java

Issue 2057 shows that letter-spacing was ignored in width calculations.
This PR solves this.
[issue-2057.zip](https://github.com/user-attachments/files/18963269/issue-2057.zip)

Fix issue 2057: Take letter-spacing into account for width calculation

---

engine/org.eclipse.birt.report.engine.emitter.docx/src/org/eclipse/birt/report/engine/emitter/docx/writer/Document.java
engine/org.eclipse.birt.report.engine.emitter.docx/src/org/eclipse/birt/report/engine/emitter/docx/writer/DocxWriter.java
engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/AbstractEmitterImpl.java
engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/IWordWriter.java
engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/writer/AbstractWordXmlWriter.java
engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/writer/DocWriter.java

The showHeaderOnFirst property did not work for the DOCX emitter when using the combined RunAndRenderTask.
That is, the header was shown on the first page even when the property was false).
This PR makes this work.
It works with RunAndRenderTask as well as with separate RunTask and RenderTask.
The related property showFooterOnLast does not work with RunAndRenderTask,
only with separate RunTask and RenderTask.

Fix docx header issue #2026

---

build/org.eclipse.birt.releng.maven/BIRT-Runtime-Minimized.aggr
build/org.eclipse.birt.releng.maven/BIRT-Runtime.aggr

- Exclude sampledb
- Exclude chart examples
- Remove `.feature.group` suffix from runtime artifacts
https://github.com/eclipse-birt/birt/issues/625

Update *.aggr for Maven publishing

---

Jenkinsfile
build/org.eclipse.birt.p2updatesite/pom.xml
build/org.eclipse.birt.target/org.eclipse.birt.target.target

- Update the target platform.
- Try to build mvn using less RAM to avoid out-of-memory when promoting.

Ensure that the p2 repository has all available sources

---

engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/util/SecurityUtil.java

Create a copy of the global shared `System.getProperties()` to prevent a `ConcurrentModificationException` from being thrown while iterating in `executionContext.registerBeans(systemProperties)`

Synchronize System.getProperties() access

---

Jenkinsfile
build/org.eclipse.birt.target/org.eclipse.birt.target.target
pom.xml

- Use export MAVEN_OPTS="-XX:MaxRAMPercentage=30" to avoid heap space errors creating the update site zip.
- Use regenerated target platform with stricter versions for "org.mortbay.jasper to avoid resolving the 10.x versions.

Update to Tycho 4.0.13

---

viewer/org.eclipse.birt.report.viewer/src/org/eclipse/birt/report/viewer/utilities/ViewerWebApp.java

- Without this, there is an NPE for jetty 12.0.24 in org.eclipse.jetty.ee8.servlet.ServletHolder.initJspServlet().
- Use system property value of IBirtConstants.SYS_PROP_WORKING_PATH which is generally expected to be available because it's used in the configuration files.
https://github.com/eclipse-birt/birt/issues/2259

ContextHandler.setAttribute for ServletContext.TEMPDIR

---

build/org.eclipse.birt.releng.maven/publishToMaven.jenkinsfile
build/org.eclipse.birt.releng/BIRT.setup
build/org.eclipse.birt.target/org.eclipse.birt.target.target

- Use permanent URLs so that branch can be built in the future.
- Update the maven publishing pipeline to the state used for publishing the 4.21 release.
https://github.com/eclipse-birt/birt/issues/2184

Lock down the target platform for the 4.21 release
