- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/IPDFRenderOption.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/impl/DataExtractionTaskV0.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/impl/DatasetPreviewTask.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/impl/QueryUtil.java
Internal refactor apis to avoid IQueryDefinition.setAutoBinding 
and comment on code
> Internal refactor apis and document code

- UI/org.eclipse.birt.report.designer.ui.data/src/org/eclipse/birt/report/designer/data/ui/dataset/OutParameterPreviewTask.java
- UI/org.eclipse.birt.report.designer.ui.preview.test/test/org/eclipse/birt/report/designer/ui/preview/parameter/MockGetParameterDefinitionTask.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/impl/QueryUtil.java
> Fix compile errors.

- model/org.eclipse.birt.report.model.adapter.oda/src/org/eclipse/birt/report/model/adapter/oda/impl/ROMResultSetsHelper.java
> Code Refactor: Resolve Column name related issue.

- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/api/APICompatibleTest.java
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/util/BaseTestCase.java
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/util/DesignFileCompareUtil.java
> Fix Bug447748 Code Refactor to fix report.model test failures.

- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/impl/QueryUtil.java
fix bug 456561 defensive code to avoid NPE
> fix bug 456561 defensive code to avoid NPE

- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/impl/DatasetPreviewTask.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/impl/QueryUtil.java
Refactor on ResultSetColumn structure
> Refactor on ResultSetColumn structure

- xtab/org.eclipse.birt.report.item.crosstab.core/plugin.xml
- xtab/org.eclipse.birt.report.item.crosstab.core/src/org/eclipse/birt/report/item/crosstab/core/de/internal/CrosstabReportItemTask.java
- xtab/org.eclipse.birt.report.item.crosstab.core/src/org/eclipse/birt/report/item/crosstab/core/de/internal/CrosstabViewTask.java
- xtab/org.eclipse.birt.report.item.crosstab.core/src/org/eclipse/birt/report/item/crosstab/core/i18n/nls.properties
- xtab/org.eclipse.birt.report.item.crosstab.core/src/org/eclipse/birt/report/item/crosstab/core/re/CrosstabQueryUtil.java
- xtab/org.eclipse.birt.report.item.crosstab.core/src/org/eclipse/birt/report/item/crosstab/core/util/CrosstabUtil.java
- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/internal/ui/dnd/DataColumnXTabDropAdapter.java
- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/internal/ui/editors/action/AddRelativeTimePeriodAction.java
- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/ui/views/attributes/widget/CrosstabBindingComboPropertyDescriptor.java
- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/ui/views/dialogs/CrosstabHighlightRuleBuilder.java
- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/ui/views/dialogs/CrosstabMapRuleBuilder.java
> Code Enhancement: Dimension related feature enhancement.

- xtab/org.eclipse.birt.report.item.crosstab.core/src/org/eclipse/birt/report/item/crosstab/core/de/internal/CrosstabModelUtil.java
- xtab/org.eclipse.birt.report.item.crosstab.core/src/org/eclipse/birt/report/item/crosstab/core/util/CrosstabUtil.java
- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/internal/ui/dialogs/CrosstabBindingDialogHelper.java
- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/internal/ui/editors/action/AddRelativeTimePeriodAction.java
> Code Enhancement: Parse correct expression for crosstab.

- xtab/org.eclipse.birt.report.item.crosstab.core/src/org/eclipse/birt/report/item/crosstab/core/util/CrosstabUtil.java
- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/internal/ui/editors/action/AddLevelHandleAction.java
> Code Fix: Add support to prevent NPE

- engine/org.eclipse.birt.report.engine.emitter.config.pptx/src/org/eclipse/birt/report/engine/emitter/config/pptx/PPTXEmitterDescriptor.java
- engine/org.eclipse.birt.report.engine.emitter.config.pptx/src/org/eclipse/birt/report/engine/emitter/config/pptx/i18n/messages.properties
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/data/dte/ReportQueryBuilder.java
-pagination option is added on export option
-api enhancement for extension
> PPTX pagination option and internal refactor

- UI/org.eclipse.birt.report.designer.ui.data/src/org/eclipse/birt/report/designer/data/ui/dataset/OutParameterPreviewTask.java
> Fixed a compile error.

- engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/MetadataEmitter.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/data/dte/ReportQueryBuilder.java
-Fixed not able to view report due to setDetails change.
-enhancement for extension
> fixed preview report and internal refactor

- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/executor/ListingElementExecutor.java
Query on data item is a summary table, only one data row It's expected result. 
> Fixed bug 457092. 

- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/content/impl/AbstractContent.java
Force save contents to report document if alt text is set
> fixed bug 457094 : 

- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/presentation/LocalizedContentVisitor.java
Modify the image cache ID, add height,width and their unit to cache ID
> fixed bug 457095

- engine/org.eclipse.birt.report.engine.emitter.config/src/org/eclipse/birt/report/engine/emitter/config/impl/EmitterConfigurationManager.java
- engine/org.eclipse.birt.report.engine.emitter.config/src/org/eclipse/birt/report/engine/emitter/config/impl/EmitterConfigurationManagerFactory.java
> Performance refactor

- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/executor/optimize/ExecutionOptimize.java
The alternative text expression of Label or Data item doesn't work inside the nested Table or Grid
> Refactor operation

- engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLReportEmitter.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/impl/RenderTask.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/executor/ListingElementExecutor.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/html/HTMLReportLayoutEngine.java
fixed bug 457392
fixed bug 457395
Refactor change execution sequence of beforeRender
Refactor: Alignment issue for the column header of merged cells
fix bug 457397
fixing bug 457397
> Refactor internal issues

- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/olap/query/view/QueryExecutorV1.java
> Fix for Bug 401068 - Files resouces are notgetting released by BIRT

- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXCanvas.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TableWriter.java
> PPTX: Implementation of table export: simple table

- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TableWriter.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TextWriter.java
> Refactor fixes for PPTX

- engine/org.eclipse.birt.report.engine.emitter.config.pptx/META-INF/MANIFEST.MF
- engine/org.eclipse.birt.report.engine.emitter.config.pptx/src/org/eclipse/birt/report/engine/emitter/config/pptx/PPTXEmitterDescriptor.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXRender.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TextWriter.java
It will contain the option to chose edit mode and there is modulation of table and text
> Refactor implementation of PPTX emitter editable

- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXRender.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TextWriter.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/writer/Presentation.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/writer/Theme.java
Refactor implementation of PPTX emitter text and masterpage
> Refactor implementation of PPTX emitter text and masterpage

- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXCanvas.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXRender.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/SlideWriter.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TableWriter.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TextWriter.java
Refactor text and table in PPTX emitter
> Refactor implementation of PPTX emitter

- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXCanvas.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXRender.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TableWriter.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TextWriter.java
Improve the details on cell size on table and text alignments
> Refactor implementation of PPTX emitter text and table features

- engine/org.eclipse.birt.report.engine.emitter.config.pptx/src/org/eclipse/birt/report/engine/emitter/config/pptx/i18n/messages.properties
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXCanvas.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXRender.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TableVisitor.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TableWriter.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TextWriter.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TreeVisitor.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/util/PPTXUtil.java
Refactor styling and hyperlink
> Refactor implementation of PPTX emitter table and text

- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXRender.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TableWriter.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/util/PPTXUtil.java
> Refactor margin on table cell

- UI/org.eclipse.birt.report.designer.tests/test/org/eclipse/birt/report/designer/core/commands/CmdBaseTestCase.java
- UI/org.eclipse.birt.report.designer.tests/test/org/eclipse/birt/report/designer/testutil/BirtUITestCase.java
- UI/org.eclipse.birt.report.designer.tests/test/org/eclipse/birt/report/designer/util/CSSUtilTest.java
> Fix unit test cases.

- viewer/org.eclipse.birt.report.viewer/src/org/eclipse/birt/report/viewer/utilities/WebViewer.java
- xtab/org.eclipse.birt.report.item.crosstab.core/src/org/eclipse/birt/report/item/crosstab/core/de/internal/CrosstabModelUtil.java
- xtab/org.eclipse.birt.report.item.crosstab.core/src/org/eclipse/birt/report/item/crosstab/core/re/CrosstabQueryUtil.java
- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/internal/ui/AggregationDropAdapter.java
- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/internal/ui/dialogs/CrosstabBindingDialogHelper.java
- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/internal/ui/dnd/DimensionHandleDropAdapter.java
- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/internal/ui/editors/action/AddLevelHandleAction.java
- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/internal/ui/editors/action/AddRelativeTimePeriodAction.java
- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/internal/ui/editors/commands/AddLevelAttributeHandleCommand.java
> Merge changes to OS BIRT

- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TextWriter.java
> Refactor Text on PPTX

- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/TableArea.java
> Refactor for tablearea to show size

- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TextWriter.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/executor/GroupExecutor.java
Fix issue on dynamic parameter and pptx textbox
> Refactor text box in PPTX and dynamic parameter

- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/util/SvgFile.java
> Refactor change SVG file from JPEG to PNG

- nl/org.eclipse.birt.report.engine.emitter.config.pptx.nl/src/org/eclipse/birt/report/engine/emitter/config/pptx/i18n/messages_de_DE.msg
- nl/org.eclipse.birt.report.engine.emitter.config.pptx.nl/src/org/eclipse/birt/report/engine/emitter/config/pptx/i18n/messages_es_ES.msg
- nl/org.eclipse.birt.report.engine.emitter.config.pptx.nl/src/org/eclipse/birt/report/engine/emitter/config/pptx/i18n/messages_fr_FR.msg
- nl/org.eclipse.birt.report.engine.emitter.config.pptx.nl/src/org/eclipse/birt/report/engine/emitter/config/pptx/i18n/messages_ja_JP.msg
- nl/org.eclipse.birt.report.engine.emitter.config.pptx.nl/src/org/eclipse/birt/report/engine/emitter/config/pptx/i18n/messages_ko_KR.msg
- nl/org.eclipse.birt.report.engine.emitter.config.pptx.nl/src/org/eclipse/birt/report/engine/emitter/config/pptx/i18n/messages_zh_CN.msg
> Refactor messages.properties on PPTX

- engine/org.eclipse.birt.report.engine.emitter.config.pptx/src/org/eclipse/birt/report/engine/emitter/config/pptx/PPTXEmitterDescriptor.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXCanvas.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXRender.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/SlideWriter.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TableWriter.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TextWriter.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/writer/PPTXBookmarkManager.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/writer/Presentation.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/writer/Slide.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/writer/SlideMaster.java
- engine/org.eclipse.birt.report.engine.ooxml/src/org/eclipse/birt/report/engine/ooxml/IPart.java
- engine/org.eclipse.birt.report.engine.ooxml/src/org/eclipse/birt/report/engine/ooxml/PartContainer.java
- engine/org.eclipse.birt.report.engine.ooxml/src/org/eclipse/birt/report/engine/ooxml/PartReference.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/impl/RenderTask.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/data/dte/DataInteractiveEngine.java
Refactor hyperlink/bookmark for PPTX and remove incompatible items
> Refactor hyperlink for PPTX and remove incompatible items

- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/data/dte/DataInteractiveEngine.java
> Refactor internal

- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXCanvas.java
- engine/org.eclipse.birt.report.engine.ooxml/src/org/eclipse/birt/report/engine/ooxml/PartContainer.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/impl/RunTask.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/data/dte/DataInteractiveEngine.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/executor/ApplicationClassLoader.java
refactor script library null path handle
refactor hyperlink/bookmark on image and other cases
refactor image on negative width
initialize correctly cube query
refactor change execution order to check layout
> Refactor null handle on queries and pptx corrupt files

- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXRender.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/executor/ListingElementExecutor.java
Refactor implementation of PPTX emitter editable and max limit on report design
> Refactor implementation of PPTX emitter editable and max limit on report design

- engine/org.eclipse.birt.report.engine.emitter.config.pdf/src/org/eclipse/birt/report/engine/emitter/config/pdf/PDFEmitterDescriptor.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/ContainerArea.java
Refactor documentation and passing items
> Refactor documentation and passing clone attributes

- engine/org.eclipse.birt.report.engine.emitter.config.pptx/src/org/eclipse/birt/report/engine/emitter/config/pptx/PPTXEmitterDescriptor.java
> Align correct preview with export content on PPTX

- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TextWriter.java
> Refactor pptx text with correct height

- UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/nls/messages.properties
- model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/core/namespace/AbstractNameHelper.java
- model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/i18n/Messages.properties
- xtab/org.eclipse.birt.report.item.crosstab.core/src/org/eclipse/birt/report/item/crosstab/core/util/CrosstabUtil.java
- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/internal/ui/dnd/ExtendedDataColumnXtabDropAdapter.java
- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/internal/ui/editors/commands/AddDimensionViewHandleCommand.java
- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/internal/ui/editors/commands/CreateDimensionViewCommand.java
> Add messages to enhance product features.

- model/org.eclipse.birt.report.model.adapter.oda.tests/test/org/eclipse/birt/report/model/adapter/oda/api/AdvancedDataSetAdapterTest.java
- model/org.eclipse.birt.report.model.adapter.oda.tests/test/org/eclipse/birt/report/model/adapter/oda/api/DataSetParameterAdapterTest.java
- model/org.eclipse.birt.report.model.adapter.oda.tests/test/org/eclipse/birt/report/model/adapter/oda/api/OdaDataSetAdapterTest.java
- model/org.eclipse.birt.report.model.adapter.oda.tests/test/org/eclipse/birt/report/model/adapter/oda/api/OdaDataSourceAdapterTest.java
- model/org.eclipse.birt.report.model.adapter.oda.tests/test/org/eclipse/birt/report/model/adapter/oda/api/ReportParameterAdapterTest.java
- model/org.eclipse.birt.report.model.adapter.oda.tests/test/org/eclipse/birt/report/model/adapter/oda/api/ResultSetColumnAdapterTest.java
- model/org.eclipse.birt.report.model.adapter.oda.tests/test/org/eclipse/birt/report/model/adapter/oda/api/input/DataSetParamConvertTest_1.xml
- model/org.eclipse.birt.report.model.adapter.oda.tests/test/org/eclipse/birt/report/model/adapter/oda/api/input/OdaDataSetConvertReportParamTest_1.xml
- model/org.eclipse.birt.report.model.adapter.oda.tests/test/org/eclipse/birt/report/model/adapter/oda/api/input/OdaDataSetConvertResultSetsTest.xml
- model/org.eclipse.birt.report.model.adapter.oda.tests/test/org/eclipse/birt/report/model/adapter/oda/api/input/OdaDataSetConvertResultSetsTest_1.xml
- model/org.eclipse.birt.report.model.adapter.oda.tests/test/org/eclipse/birt/report/model/adapter/oda/api/input/OdaDataSetConvertResultSetsTest_2.xml
- model/org.eclipse.birt.report.model.adapter.oda.tests/test/org/eclipse/birt/report/model/adapter/oda/util/BaseTestCase.java
- model/org.eclipse.birt.report.model.adapter.oda/src/org/eclipse/birt/report/model/adapter/oda/impl/DataSetAdapter.java
Signed-off-by: Yuxuan Dai <ydai@actuate.com>
> Fixed utest for model.adapter.oda

- core/org.eclipse.birt.core.tests/test/org/eclipse/birt/core/AllTests.java
- core/org.eclipse.birt.core.tests/test/org/eclipse/birt/core/archive/ArchiveUtilTest.java
- core/org.eclipse.birt.core.tests/test/org/eclipse/birt/core/format/DateFormatterTest.java
- Description of Issue: 
Some unit tests are failed, need to look into the issue.
- Description of Resolution: 
Fixed / updated some unit tests.
> - Summary: Fix utest for core

- engine/org.eclipse.birt.report.engine.tests/test/org/eclipse/birt/report/engine/api/EngintTaskLoggerTest.java
- engine/org.eclipse.birt.report.engine.tests/test/org/eclipse/birt/report/engine/ir/ir_io_test_V1.xml
- engine/org.eclipse.birt.report.engine.tests/test/org/eclipse/birt/report/engine/ir/ir_io_test_V2.xml
- engine/org.eclipse.birt.report.engine.tests/test/org/eclipse/birt/report/engine/ir/ir_io_test_V3.xml
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/impl/EngineTask.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/internal/executor/dup/SuppressDuplicateUtil.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/internal/index/v2/IndexReader.java
> Report engine Junit test fix2.

- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/api/golden/ActionHandleTest3_golden.xml
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/api/golden/ActionHandleTest4_golden.xml
The tag precessing order was changed, modify the golden file to accommodate the change
> model unit test fix

- testsuites/org.eclipse.birt.report.tests.engine/src/org/eclipse/birt/report/tests/engine/api/DataExtractionTaskTest.java
- testsuites/org.eclipse.birt.report.tests.engine/src/org/eclipse/birt/report/tests/engine/api/DataIDTest.java
- testsuites/org.eclipse.birt.report.tests.engine/src/org/eclipse/birt/report/tests/engine/api/DataSetIDTest.java
- testsuites/org.eclipse.birt.report.tests.engine/src/org/eclipse/birt/report/tests/engine/api/HTMLServerImageHandlerTest.java
- testsuites/org.eclipse.birt.report.tests.engine/src/org/eclipse/birt/report/tests/engine/api/IColumnTest.java
- testsuites/org.eclipse.birt.report.tests.engine/src/org/eclipse/birt/report/tests/engine/api/IDataIteratorTest.java
- testsuites/org.eclipse.birt.report.tests.engine/src/org/eclipse/birt/report/tests/engine/api/IGetParameterDefinitionTaskTest.java
- testsuites/org.eclipse.birt.report.tests.engine/src/org/eclipse/birt/report/tests/engine/api/RenderFolderDocumentTest.java
- testsuites/org.eclipse.birt.report.tests.engine/src/org/eclipse/birt/report/tests/engine/api/RenderTaskTest.java
- testsuites/org.eclipse.birt.report.tests.engine/src/org/eclipse/birt/report/tests/engine/api/ReportParameterConverterTest.java
All test cases now pass.  I ran them with target environment of Mars M6 build.
> DSG-531 Fix utest for tests.engine

- testsuites/org.eclipse.birt.report.tests.model/src/org/eclipse/birt/report/tests/model/api/DesignElementHandleTest.java
- testsuites/org.eclipse.birt.report.tests.model/src/org/eclipse/birt/report/tests/model/regression/Regression_136809.java
- testsuites/org.eclipse.birt.report.tests.model/src/org/eclipse/birt/report/tests/model/regression/Regression_148761.java
- testsuites/org.eclipse.birt.report.tests.model/src/org/eclipse/birt/report/tests/model/regression/Regression_152699.java
- testsuites/org.eclipse.birt.report.tests.model/src/org/eclipse/birt/report/tests/model/regression/Regression_155167.java
- testsuites/org.eclipse.birt.report.tests.model/src/org/eclipse/birt/report/tests/model/regression/Regression_155356.java
- testsuites/org.eclipse.birt.report.tests.model/src/org/eclipse/birt/report/tests/model/regression/Regression_79091.java
- testsuites/org.eclipse.birt.report.tests.model/src/org/eclipse/birt/report/tests/model/regression/golden/Reg_75539.golden
- testsuites/org.eclipse.birt.report.tests.model/src/org/eclipse/birt/report/tests/model/regression/golden/Regression_121352_golden.xml
- testsuites/org.eclipse.birt.report.tests.model/src/org/eclipse/birt/report/tests/model/regression/golden/regression_149922.golden
- testsuites/org.eclipse.birt.report.tests.model/src/org/eclipse/birt/report/tests/model/regression/input/regression_148761.xml
Signed-off-by: Yuxuan Dai <ydai@actuate.com>
> Fixed unit test for tests.model.

- model/org.eclipse.birt.report.model.testresources/META-INF/MANIFEST.MF
- model/org.eclipse.birt.report.model.testresources/pom.xml
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/core/golden/CellLocalPropsTest_golden.txt
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/core/golden/CellPropsTest_golden.txt
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/core/golden/DesignElementCloneTest_ImageClone_golden.xml
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/core/golden/ImageLocalPropsTest_golden.txt
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/core/golden/ImagePropsTest_golden.txt
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/core/golden/TableItemPropsTest_golden.txt
- model/org.eclipse.birt.report.modelextension.tests/META-INF/MANIFEST.MF
- model/org.eclipse.birt.report.modelextension.tests/build.properties
- model/org.eclipse.birt.report.modelextension.tests/pom.xml
- testsuites/pom.xml
Add pom file for the plugins added in model;
Modify some golden files to accommodate souce code changes;
> Add pom file for the plugins added in model

- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/command/ExtendsCommandTest.java
- model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/command/ExtendsCommand.java
> Fix Report Model Unit test issues.

- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/extension/golden/ExtensionTest_AltText_golden.xml
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/extension/golden/ExtensionTest_golden_1.xml
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/extension/golden/ExtensionTest_golden_2.xml
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/extension/golden/ExtensionTest_golden_3.xml
> Fix Unit test report model extension tests.

- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/core/golden/DeisgnElementCloneTest_gridClone_golden.xml
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/core/golden/TableItemLocalPropsTest_golden.txt
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/core/golden/TableItemPropsTest_golden.txt
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/core/input/DesignElementTest_3.xml
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/extension/golden/PeerExtensionTest_golden.xml
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/extension/golden/PeerExtensionTest_golden_1.xml
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/extension/golden/PeerExtensionTest_golden_2.xml
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/extension/golden/PeerExtensionTest_golden_3.xml
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/i18n/PropertyLocalizationTest.java
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/library/LibraryWithTableTest.java
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/library/golden/TestDropLibrary_golden1.xml
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/library/golden/TestDropLibrary_golden2.xml
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/metadata/DateTimePropertyTypeTest.java
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/metadata/ElementDefnTest.java
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/metadata/MetaLoggerTest.java
- model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/i18n/Messages.properties
> Fix some failed unit tests in model

- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/parser/ParserCompatibilityTest.java
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/parser/golden/ImageItemParseTest_golden.xml
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/parser/golden/action_test_golden.xml
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/parser/golden/action_test_golden_1.xml
- model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/parser/ExtendedPropertyState.java
- model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/writer/ModuleWriterImpl.java
> Fix failed parser-related unit tests

- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/writer/golden/DocumentUtilTest_external_selectors_golden.xml
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/writer/golden/DocumentUtilTest_golden_2.xml
> Modify golden files to accommodate code changes.

- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/validators/MasterPageSizeValidatorTest.java
> Comment the assertions for temporary fix. Uncomment it if bug DSG-674 is

- build/org.eclipse.birt.runtime.osgi/.project
- build/org.eclipse.birt.runtime.osgi/birtsdk.product
- build/org.eclipse.birt.runtime.osgi/build.properties
- build/org.eclipse.birt.runtime.osgi/feature.xml
- build/org.eclipse.birt.runtime.osgi/pom.xml
- build/pom.xml
> Add project build/org.eclipse.birt.runtime.osgi for BIRT SDK.

- UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/util/DEUtil.java
> use new default library ThemesReportItem31.rptlibrary

- build/org.eclipse.birt.testSuites/category.xml
- build/org.eclipse.birt.testSuites/pom.xml
${birt.version} needs to be set in the main pom
> pom and category file to create birt-tests-suite package.

- build/birt-packages/birt-report-framework-sdk/category.xml
- build/birt-packages/birt-report-framework-sdk/pom.xml
- build/birt-packages/birt-report-framework/category.xml
- build/birt-packages/birt-report-framework/pom.xml
- build/birt-packages/pom.xml
- build/pom.xml
- features/org.eclipse.birt.example.feature/feature.xml
- pom.xml
> Add birt-report-framework and birt-report-framework-sdk package.

- build/org.eclipse.birt.testSuites/pom.xml
> Remove time stamp

- build/birt-packages/birt-charts/ChartRuntime/pom.xml
- build/birt-packages/birt-charts/ChartSDK/pom.xml
- build/birt-packages/birt-charts/DeploymentRuntime/pom.xml
- build/birt-packages/birt-charts/pom.xml
> Fix mvn install issue in birt-charts.

- build/birt-packages/birt-report-designer-all-in-one/.project
- build/birt-packages/birt-report-designer-all-in-one/BIRT.product
- build/birt-packages/birt-report-designer-all-in-one/pom.xml
> Add product project for all-in-one package.

- build/birt-packages/birt-charts/pom.xml
> Minor change in birt-charts.

- build/birt-packages/birt-report-all-in-one/BIRT.product
- pom.xml
> Fix the build process to add the missing information to the "About" dlg

- engine/org.eclipse.birt.report.engine.dataextraction.csv.tests/META-INF/MANIFEST.MF
- engine/org.eclipse.birt.report.engine.dataextraction.csv/META-INF/MANIFEST.MF
> Expose the mock packege in csv.tests.

- UI/org.eclipse.birt.report.designer.ui.views/src/org/eclipse/birt/report/designer/ui/views/attributes/BasePageGenerator.java
- UI/org.eclipse.birt.report.designer.ui.views/src/org/eclipse/birt/report/designer/ui/views/attributes/IPageGeneratorHelper.java
>     - Summary: Allow for customization of the property editor by adding

- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/olap/impl/query/CubeQueryDefinition.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/data/dte/ReportQueryBuilder.java
> Revert "Engine adds join information when creating queries"

- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/data/dte/AbstractDataEngine.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/data/dte/ReportQueryBuilder.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/data/dte/ReportQueryBuilderFactory.java
Now it uses a factory to create ReportQueryBuilders.
> Refactor ReportQueryBuilder.

- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/api/ICombinedOdaDataSetDesign.java
- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/api/querydefn/CombinedOdaDataSetDesign.java
- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/api/script/IDataSetInstanceHandle.java
- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/impl/CombinedOdaDataSetRuntime.java
- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/impl/DataSetRuntime.java
- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/impl/IQueryOptimizeHints.java
- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/impl/PreparedCombinedOdaDSQuery.java
- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/impl/PreparedOdaDSQuery.java
- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/impl/PreparedQueryUtil.java
- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/impl/QueryOptimizeHints.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/adapter/ModelDteApiAdapter.java
> Support combined Oda data Set.

- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/script/internal/instance/DataSetInstance.java
> Fix compile error.

- UI/org.eclipse.birt.report.designer.ui.cubebuilder/src/org/eclipse/birt/report/designer/ui/cubebuilder/dialog/IMeasureDialogHelper.java
- UI/org.eclipse.birt.report.designer.ui.cubebuilder/src/org/eclipse/birt/report/designer/ui/cubebuilder/dialog/MeasureDialog.java
- Description of Issue: Enable customization of MeasureDialog.
- Description of Resolution:
- Regression ( Yes/No ): No
- Code Owner Team: BIRT
- Code Reviewers:
- Project ID:
- Manual Test Description: Debug in dev env
- Tests Automated Cases Executed:
- Special Notes:
> - Summary: Make MeasureDialog more extensible.

- chart/org.eclipse.birt.chart.reportitem.ui/src/org/eclipse/birt/chart/reportitem/ui/dialogs/ChartExpressionProvider.java
When series is a pre-defined aggregation, the expression should start with
prefix "data."  Otherwise, use normal behavior.
> Chart Builder - support extended pre-defined aggregation.

- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/api/querydefn/QueryDefinition.java
- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/olap/impl/query/CubeQueryDefinition.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/impl/QueryUtil.java
> Fix cloning bug. Links need to be cloned also.

- UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/nls/messages.properties
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/views/actions/InsertAction.java
> BIRT 1388: Incorrect wording in context menu to create a new master page

- chart/org.eclipse.birt.chart.reportitem.ui/src/org/eclipse/birt/chart/reportitem/ui/ChartExpressionButton.java
> When you drop a measure the expression should have data indicator.

- UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/nls/messages.properties
> Fix remaining capitalization issue for creating a new master page

- UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/nls/messages.properties
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/ui/dialogs/ExpressionProvider.java
> Add a constant string to expression provider called available measures.

- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/api/IQueryDefinition.java
- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/api/querydefn/BaseQueryDefinition.java
- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/api/querydefn/QueryDefinition.java
> Support clone operation on IQueryDefinition.

- UI/org.eclipse.birt.report.designer.ui.data/src/org/eclipse/birt/report/designer/data/ui/dataset/ExternalUIUtil.java
- data/org.eclipse.birt.report.data.oda.jdbc.ui/src/org/eclipse/birt/report/data/oda/jdbc/ui/editors/OdaConnectionProvider.java
Signed-off-by: Rick Lu <rlu@actuate.com>
> fixed UI issues when DtE tries to resolve resource path.

- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/dialogs/DataColumnBindingDialog.java
- xtab/org.eclipse.birt.report.item.crosstab.core/src/org/eclipse/birt/report/item/crosstab/core/de/CrosstabReportItemHandle.java
- xtab/org.eclipse.birt.report.item.crosstab.core/src/org/eclipse/birt/report/item/crosstab/core/util/CrosstabUtil.java
- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/internal/ui/dialogs/CrosstabBindingDialogHelper.java
> Crosstab support for measures that don't belong to cubes.

- xtab/org.eclipse.birt.report.item.crosstab.core/src/org/eclipse/birt/report/item/crosstab/core/de/internal/CrosstabModelUtil.java
> Make logic more simple.  If it already exists, do not recreate.

- UI/org.eclipse.birt.report.designer.ui.views/src/org/eclipse/birt/report/designer/ui/views/attributes/AttributesBuilder.java
- UI/org.eclipse.birt.report.designer.ui.views/src/org/eclipse/birt/report/designer/ui/views/attributes/TabPageGenerator.java
> Better support for extended page generators.

- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/internal/ui/dialogs/CrosstabBindingDialogHelper.java
> Fix NullPointerException in crosstab binding dialog.

- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/internal/ui/editors/model/CrosstabAdaptUtil.java
> Fix crosstab measure view alignment and hyperlink.

- UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/core/commands/PasteCommand.java
- UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/util/DNDUtil.java
- Description of Issue: copy/paste does not work on same way when Click
in DM.  
It was tested manually.  As unit test was not possible because original
code was in designer.core
> - Summary: consistency on copy/paste in DataDesign on designer

- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/views/RenameInputDialog.java
> Removed unnecessary error messages inside property editor dialogue

- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/font/FontInfo.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/impl/TextCompositor.java
italic
- Description of Issue:  If the font does not contain the italic,
justify is lost
- Description of Resolution:  correct the layout process on simulate
italic
> - Summary: Justification lost when using a font that does not support

- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXCanvas.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TableWriter.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TextWriter.java
- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/writer/SlideMaster.java
- Description of Issue:  the produce NPE and also another issue is found
on merging cells.
- Description of Resolution:  ignore image if not found.
> - Summary: PPTX emitter cannot generate when image does not exist

- UI/org.eclipse.birt.report.designer.ui.views/src/org/eclipse/birt/report/designer/internal/ui/views/attributes/widget/AggregateOnBindingsFormDescriptor.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/dialogs/DataColumnBindingDialog.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/dialogs/DataSetColumnBindingsFormPage.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/views/dialogs/provider/DataSetColumnBindingsFormHandleProvider.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/ui/dialogs/ColumnBindingDialog.java
- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/internal/ui/dialogs/CrosstabBindingDialogHelper.java
> Support for extended datasets with predefined aggregations.

- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/api/querydefn/BaseQueryDefinition.java
- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/api/querydefn/QueryDefinition.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/data/dte/ReportQueryBuilder.java
> support getParentQuery inside nested xtab

- xtab/org.eclipse.birt.report.item.crosstab.core/src/org/eclipse/birt/report/item/crosstab/core/de/internal/CrosstabModelUtil.java
> Failed to define total for crosstab with predefined aggregated measures

- engine/org.eclipse.birt.report.engine.dataextraction.csv.tests/test/org/eclipse/birt/report/engine/dataextraction/csv/CSVUtilTest.java
> fix CSVUtilTest cases.  A bug fix did not update the test cases.

- build/birt-packages/birt-integration-test/pom.xml
- build/birt-packages/pom.xml
> Add Unit Test for OS BIRT viewer

- data/org.eclipse.birt.data.tests/test/org/eclipse/birt/data/engine/olap/data/impl/facttable/TestTimeDimension.java
Ignore TestTimeDimension test in package
org.eclipse.birt.data.engine.olap.data.impl.facttable
> Ignore TestTimeDimension.testTimeDimension()

- build/birt-packages/birt-runtime-test/pom.xml
- build/birt-packages/birt-runtime-test/src/test/java/org/eclipse/birt/sdk/BaseTestTemplate.java
- build/birt-packages/birt-runtime-test/src/test/java/org/eclipse/birt/sdk/RuntimeOSGiTest.java
- build/birt-packages/birt-runtime-test/src/test/java/org/eclipse/birt/sdk/RuntimeTest.java
1. add unit test for OS SDK OSGi
2. refactor unit test for OS SDK jar to reuse resources
> Add unit test for OS SDK OSGi

- features/org.eclipse.birt.chart.cshelp.feature/feature.properties
- features/org.eclipse.birt.cshelp.feature/feature.properties
- features/org.eclipse.birt.doc.feature/feature.properties
- features/org.eclipse.birt.example.feature/feature.properties
- features/org.eclipse.birt.feature/feature.properties
- features/org.eclipse.birt.osgi.runtime.sdk/feature.properties
- features/org.eclipse.birt.osgi.runtime/feature.properties
- features/org.eclipse.birt.report.designer.editor.xml.wtp.feature/feature.properties
Update from 2011 to 2014.
The features affected were found in the license inconsistency report.
> Update Eclipse license in feature.properties.

- build/org.eclipse.birt/build.properties
> Include about.html in source package.

- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/editors/parts/GraphicalEditorWithFlyoutPalette.java
> Summary: Report layout editor, pop-up menu, "Delete", not localized.

- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/internal/ui/views/provider/AreaNodeProvider.java
- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/ui/i18n/nls.properties
Externalize hard coded string "Headers" which appears in outline view.
> Fixing problem introduced by commit ID 2c509f91 in March 20th, 2012.

- engine/org.eclipse.birt.report.engine.dataextraction.csv.tests/test/org/eclipse/birt/report/engine/dataextraction/csv/testSelectInvalidColumn.csv
- engine/org.eclipse.birt.report.engine.tests/test/org/eclipse/birt/report/engine/api/impl/DataExtractionTaskTest.java
missing a file for test and one test case is not supported on open source
> missing checkin and a no supported remove no supported test case

- build/birt-packages/birt-runtime-osgi/build.xml
- build/org.eclipse.birt.releng.birtbuilder/extras/genReportGenerator.sh
Added genReport.bat and genReport.sh back to Report Engine package
> Added genReport.bat and genReport.sh back to Report Engine package

- build/birt-packages/birt-runtime-osgi/build.xml
- core/org.eclipse.birt.core.tests/test/org/eclipse/birt/core/archive/DocumentArchiveTest.java
- core/org.eclipse.birt.core.tests/test/org/eclipse/birt/core/format/NumberFormatterTest.java
- data/org.eclipse.birt.data.oda.pojo.tests/src/org/eclipse/birt/data/oda/pojo/impl/ResultSetTest.java
- data/org.eclipse.birt.data.tests/test/testutil/BaseTestCase.java
- engine/org.eclipse.birt.report.engine.tests/test/org/eclipse/birt/report/engine/api/RenderTaskTest.java
- engine/org.eclipse.birt.report.engine.tests/test/org/eclipse/birt/report/engine/regression/Test_90378.java
- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/parser/OdaCubeParseTest.java
- testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_150779_Count.java
- testsuites/org.eclipse.birt.report.tests.engine/src/org/eclipse/birt/report/tests/engine/api/ReportEngineTest.java
- testsuites/org.eclipse.birt.report.tests.engine/src/org/eclipse/birt/report/tests/engine/api/RunAndRenderTaskTest.java
- testsuites/org.eclipse.birt.report.tests.engine/src/org/eclipse/birt/report/tests/engine/api/input/pages9.rptdesign
- testsuites/org.eclipse.birt.report.tests.model/src/org/eclipse/birt/report/tests/model/BaseTestCase.java
- testsuites/org.eclipse.birt.report.tests.model/src/org/eclipse/birt/report/tests/model/api/ExternalCssStyleSheet3Test.java
- testsuites/org.eclipse.birt.report.tests.model/src/org/eclipse/birt/report/tests/model/regression/Regression_148761.java
- testsuites/org.eclipse.birt.report.tests.model/src/org/eclipse/birt/report/tests/model/regression/golden/Reg_75539.golden
- testsuites/org.eclipse.birt.report.tests.model/src/org/eclipse/birt/report/tests/model/regression/golden/regression_149922.golden
- testsuites/org.eclipse.birt.tests.core/src/utility/BaseTestCase.java
- viewer/org.eclipse.birt.report.viewer.tests/test/org/eclipse/birt/report/viewer/utility/ParameterAccessorTest.java
* Fixed some core, data, engine and regression tests
* Removed \r from genReportGenerator.sh before feeding it to sh command
> Miscellaneous unit test fixes and more

- viewer/org.eclipse.birt.report.viewer/birt/test.rptdesign
Updated message in hello-world test report to better reflect its purpose.
> Updated message in test report

- build/birt-packages/birt-runtime-test/src/test/java/org/eclipse/birt/sdk/BaseTestTemplate.java
Updated unit test according to test hello-world report change
> Updated unit test according to test report change

- engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/AbstractEmitterImpl.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/content/impl/TableBandContent.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/html/HTMLBlockStackingLM.java
have same behavior as HTML for DOCX emitter
exporiting to DOCX has borders from cell impose on border from table.
> have same behavior as HTML for DOCX emitter

- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/api/aggregation/AggregationManager.java
> remove the function "range" from the list of function in data cube

- engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/AbstractEmitterImpl.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/content/impl/TableBandContent.java
As the behavior is only affected by double border on table, this is a
specific corner case.
> Revert changes from 8429ff1a7481687162179cb3e5ca34fde762fcb9

- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/ui/ReportPlatformUIImages.java
> Update the old icon in Resource Explorer when creating new Library file.

- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/IExtractionTask.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/impl/DataExtractionTask.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/impl/DataExtractionTaskV0.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/impl/DataExtractionTaskV1.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/impl/DatasetPreviewTask.java
> enhance DataExtractionTaskV1 to support overriding existing sort

- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/PPTXRender.java
resolve in the pptx emitter as it only occur PPTX.  Resolution is to
track lineArea X position
> nested <span> makes overlap of text

- viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/session/ViewingCache.java
See this forum post about the problem:
https://www.eclipse.org/forums/index.php/m/1735454/#msg_1735454
> Solved problem about Too Long java.io.IOException: File name too long

- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/executor/DataSetCacheObjectWithDummyData.java
> Alias are not recognize and create new column in metadata producing error in stream

- core/org.eclipse.birt.core/src/org/eclipse/birt/core/script/CoreJavaScriptWrapper.java
org.mozilla.javascript.NativeArray class implements List interface in
the latest release
> fix issues due to latest Rhino package change

- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/ui/dialogs/ExpressionBuilder.java
> add sorter to Javascript expression builder UI

- UI/org.eclipse.birt.report.designer.ui.ide/src/org/eclipse/birt/report/designer/ui/ide/wizards/NewReportWizard.java
Fixed this issue by setting 'theme'property using setDefaulttheme API
> Creating report design from New->BIRT Project does not use default

- UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/nls/messages.properties
- UI/org.eclipse.birt.report.designer.ui.preview.web/src/org/eclipse/birt/report/designer/ui/actions/PreviewSupport.java
- engine/org.eclipse.birt.report.engine.emitter.ppt/plugin.xml
- engine/org.eclipse.birt.report.engine.emitter.wpml/plugin.xml
- engine/org.eclipse.birt.report.engine/schema/emitters.exsd
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/EmitterInfo.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/extension/internal/ExtensionManager.java
Updated emitters to support deprecation
Deprecated DOC and PPT emitters
> BIRT-2567 Remove DOC/PPT/XLS emitters since better emitter DOCX/PPTX/XLSX supported

- UI/org.eclipse.birt.report.designer.ui.preview.web/src/org/eclipse/birt/report/designer/ui/actions/PreviewSupport.java
For better visual appearance
Signed-off-by: charlinh <charlinh@opentext.net>
> Adding a space between the format and (Deprecated) strings

- chart/org.eclipse.birt.chart.engine/src/org/eclipse/birt/chart/computation/ValueFormatter.java
-Description of Issue:
In charts tooltip value is coming upto 3 decimal points[default]
-Description of Resolution:
Added a method to valueFormatter to normalizeDouble based on pattern.  
Signed-off-by: rrimmana <rrimmana@RRIMMANA4J5LX52.opentext.net>
> Chart inherited format of data from measure partially

- data/org.eclipse.birt.report.data.adapter/src/org/eclipse/birt/report/data/adapter/impl/ModelAdapter.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/adapter/ExpressionUtil.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/impl/DatasetPreviewTask.java
Fixed code to eventually allow BIRT applications to create extended
expression script types.
> Code clean up related to extended script type support.

- data/org.eclipse.birt.data.oda.mongodb.ui/META-INF/MANIFEST.MF
- data/org.eclipse.birt.data.oda.mongodb.ui/src/org/eclipse/birt/data/oda/mongodb/ui/i18n/messages.properties
- data/org.eclipse.birt.data.oda.mongodb.ui/src/org/eclipse/birt/data/oda/mongodb/ui/impl/MongoDBAdvancedSettingsDialog.java
- data/org.eclipse.birt.data.oda.mongodb.ui/src/org/eclipse/birt/data/oda/mongodb/ui/impl/MongoDBDataSourcePageHelper.java
- data/org.eclipse.birt.data.oda.mongodb.ui/src/org/eclipse/birt/data/oda/mongodb/ui/impl/MongoDBDataSourcePropertyPage.java
- data/org.eclipse.birt.data.oda.mongodb.ui/src/org/eclipse/birt/data/oda/mongodb/ui/impl/MongoDBDataSourceWizardPage.java
- data/org.eclipse.birt.data.oda.mongodb/META-INF/MANIFEST.MF
- data/org.eclipse.birt.data.oda.mongodb/plugin.properties
- data/org.eclipse.birt.data.oda.mongodb/plugin.xml
- data/org.eclipse.birt.data.oda.mongodb/src/org/eclipse/birt/data/oda/mongodb/impl/DataSetMetaData.java
- data/org.eclipse.birt.data.oda.mongodb/src/org/eclipse/birt/data/oda/mongodb/impl/MDbConnection.java
- data/org.eclipse.birt.data.oda.mongodb/src/org/eclipse/birt/data/oda/mongodb/impl/MDbResultSet.java
- data/org.eclipse.birt.data.oda.mongodb/src/org/eclipse/birt/data/oda/mongodb/impl/MDbResultSetMetaData.java
- data/org.eclipse.birt.data.oda.mongodb/src/org/eclipse/birt/data/oda/mongodb/impl/MongoDBDriver.java
- data/org.eclipse.birt.data.oda.mongodb/src/org/eclipse/birt/data/oda/mongodb/internal/impl/ArrayFieldValues.java
- data/org.eclipse.birt.data.oda.mongodb/src/org/eclipse/birt/data/oda/mongodb/internal/impl/MDbMetaData.java
- data/org.eclipse.birt.data.oda.mongodb/src/org/eclipse/birt/data/oda/mongodb/internal/impl/MDbOperation.java
- data/org.eclipse.birt.data.oda.mongodb/src/org/eclipse/birt/data/oda/mongodb/internal/impl/QueryModel.java
- data/org.eclipse.birt.data.oda.mongodb/src/org/eclipse/birt/data/oda/mongodb/internal/impl/QueryProperties.java
- data/org.eclipse.birt.data.oda.mongodb/src/org/eclipse/birt/data/oda/mongodb/internal/impl/ResultDataHandler.java
- data/org.eclipse.birt.data.oda.mongodb/src/org/eclipse/birt/data/oda/mongodb/nls/Messages.java
- data/org.eclipse.birt.data.oda.mongodb/src/org/eclipse/birt/data/oda/mongodb/nls/messages.properties
- pom.xml
Signed-off-by: rgoteti <rgoteti@opentext.com>
> Mongodb eclipse plugin with kerberos authentication

- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/ui/dialogs/InputParameterDialog.java
reduce bug,  getparametervalue was call twice.
> Reduce multiple calls on same function will improve performance and

- data/org.eclipse.birt.data.oda.mongodb/src/org/eclipse/birt/data/oda/mongodb/impl/MDbConnection.java
MongoDB 3.2 ODA - Proper error message should be displayed for invalid
information on connection properties dialog box
Signed-off-by: rvasanth <rvasanth@RVASANTHBZ44NV1.opentext.net>
> -Description of issue :

- data/org.eclipse.birt.data.oda.mongodb.ui/src/org/eclipse/birt/data/oda/mongodb/ui/impl/MongoDBDataSourcePageHelper.java
Description of Issue: scrollbar is not coming when we resize.
Description of Resolution: added ScrolledComposite to the UI dialog
Signed-off-by: rrimmana <rrimmana@RRIMMANA4J5LX52.opentext.net>
> Summary: Scroll bar missing in MongoDB connection settings dialog box

- data/org.eclipse.birt.data.oda.mongodb/src/org/eclipse/birt/data/oda/mongodb/impl/MongoDBDriver.java
Its a backward compatibility bug.
> A report that based on Mongo ODA driver with Kerberos  authentication turned off where connection to Mongo DB, using ODA driver is throwing NPE. 

- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/executor/ExecutionContext.java
Signed-off-by: charlinh <charlinh@opentext.com>
> Check for existing DataEngine without triggering creation

- engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/PDFRender.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/emitter/PageDeviceRender.java
This will fix issue and use proper parameter naming
> comments on designer are wrongly place as description.

- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/ExcelEmitter.java
Fix to compile issue from commit 0742e65. Add default implementation for open source excel emitter
> add default implementation for open source excel emitter

- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/api/DataEngineContext.java
- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/api/querydefn/GroupDefinition.java
Changes to expost script expression in GroupDefinition.
> Changes to assign new stream identifiers.

- core/org.eclipse.birt.core/src/org/eclipse/birt/core/data/DataTypeUtil.java
- core/org.eclipse.birt.core/src/org/eclipse/birt/core/data/DateFormatISO8601.java
Signed-off-by: charlinh <charlinh@opentext.com>
> Remove multi-catch parameter to support Java 1.6 source

- core/org.eclipse.birt.core/src/org/eclipse/birt/core/data/DataTypeUtil.java
- core/org.eclipse.birt.core/src/org/eclipse/birt/core/data/DateFormatISO8601.java
Signed-off-by: charlinh <charlinh@opentext.com>
> Restore old API methods and mark them as deprecated.

- pom.xml
> Provide support for Oracle 12 and SQL Server 2016

- data/org.eclipse.birt.data.oda.mongodb/src/org/eclipse/birt/data/oda/mongodb/internal/impl/ResultDataHandler.java
Fixing the issue of fetching the appropriate field values from the result array
Signed-off-by: bsrujank <bsrujank@opentext.com>
> Fixing the issue of fetching the appropriate field values from the result array

- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/LayoutUtil.java
When there is a CellContentWrapper original will not work
> The function need to handle more generic ICellContent

- pom.xml
Added new profile to use eclipse 4.9 release
Signed-off-by: Bharadwaj Tirunagaru <btirunag@opentext.com>
> Changes to upgrade eclipse platform to 4.9 release.

- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TextWriter.java
fix for bug415818.
Signed-off-by: guans <guans@actuate.com>
> PPTX emitter doesn't honor RTL settings

- data/org.eclipse.birt.report.data.oda.jdbc.dbprofile/src/org/eclipse/birt/report/data/oda/jdbc/dbprofile/impl/Connection.java
- data/org.eclipse.birt.report.data.oda.jdbc/src/org/eclipse/birt/report/data/oda/jdbc/Connection.java
- data/org.eclipse.birt.report.data.oda.jdbc/src/org/eclipse/birt/report/data/oda/jdbc/Statement.java
VPD implementation as a BIRT function. Actual birt function is part of the commercial plugin.
> VPD implementation as a BIRT function

- data/org.eclipse.birt.report.data.oda.excel.ui/META-INF/MANIFEST.MF
- data/org.eclipse.birt.report.data.oda.excel.ui/src/org/eclipse/birt/report/data/oda/excel/ui/wizards/ExcelDataSourceWizardPage.java
- data/org.eclipse.birt.report.data.oda.jdbc.ui/src/org/eclipse/birt/report/data/oda/jdbc/ui/provider/JdbcMetaDataProvider.java
Signed-off-by: rrimmana <rrimmana@RRIMMANPF0Z2NJH.opentext.net>
> Support relative path option in ExcelDataSource wizard when creating connection profile

- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/api/impl/EngineTask.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/LayoutContext.java
Signed-off-by: Jonathan Fang <jfang@opentext.com>
> fix pdf emitter repaginate issue

- docs/org.eclipse.birt.doc.isv/BuildISVDoc.xml
Signed-off-by: Alexander Lehmann <a.lehm@gmx.de>
> Suppress Javadoc warnings that polluted the build log

- engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLReportEmitter.java
Scope changes for methods in HTMLReportEmitter to make it extendable
Signed-off-by: ajkumar <ajkumar@AJKUMARPF13G5UH.opentext.net>
> Scope changes for methods in HTMLReportEmitter

- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/layout/pdf/font/FontMappingManagerFactory.java
Signed-off-by: shiheng guan <sguan@actuate.com>
> Need access to fontpaths to create font factory

- xtab/org.eclipse.birt.report.item.crosstab.ui/src/org/eclipse/birt/report/item/crosstab/ui/views/dialogs/CrosstabFilterConditionBuilder.java
"Unhandled event loop exception" to open a filter for edit in xtab.
> Null pointer exception in filter for edit in xtab

- model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/writer/ModuleWriterImpl.java
Avoid writing password into report design in case where Connection profile is used as data source(oda)
> Avoid writing password into report design in case where Connection profile is used as data source(oda)

- engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/PDFPageDevice.java
Adding support to append and prepend PDF documents to PDF output stream.
This was previously committed, but held up due to not being a comitter
previously.
Have the ability to append boiler plate legal documentation or financial
statements to a report, the ability to append PDF files based on a
comma-seperated list or a ArrayList defined in the Report Context has
been added.
This has been tested in actual customer environments and works. To set:
-Create a BIRT Report
-Create a User Property called AppendList.
-Set AppendList under Advanced to a Comma-Seperated list of paths to PDF
files to append
-Alternatively, create an ArrayList of String in the report context set
in global variable called appendPDF.
Signed-off-by: TheLaserNinja <36558386+TheLaserNinja@users.noreply.github.com>
> Added support for Prepending and Appending PDF documents to PDF output

- .github/workflows/ci.yml
- pom.xml
Added GitHub Actions config
Signed-off-by: Alexander Fedorov <alexander.fedorov@arsysop.ru>
> Switch from Travis CI to GitHub Actions #585

- .github/workflows/ci.yml
- core/org.eclipse.birt.core.tests/.gitignore
- core/org.eclipse.birt.core.tests/pom.xml
- core/org.eclipse.birt.core.tests/test/org/eclipse/birt/core/archive/AllArchiveTests.java
- core/org.eclipse.birt.core.tests/test/org/eclipse/birt/core/archive/TestBuffer.java
- core/org.eclipse.birt.core.tests/test/org/eclipse/birt/core/btree/BTreeMultipleThreadTest.java
- core/org.eclipse.birt.core.tests/test/org/eclipse/birt/core/data/DataTypeUtilTest.java
- core/org.eclipse.birt.core.tests/test/org/eclipse/birt/core/format/DateFormatterTest.java
- core/org.eclipse.birt.core.tests/test/org/eclipse/birt/core/format/NumberFormatterTest.java
- core/org.eclipse.birt.core.tests/test/org/eclipse/birt/core/fs/LocalFileTest.java
- core/org.eclipse.birt.core.tests/test/org/eclipse/birt/core/script/bre/BirtDateTimeTest.java
- core/org.eclipse.birt.core/src/org/eclipse/birt/core/data/DataTypeUtil.java
- core/org.eclipse.birt.core/src/org/eclipse/birt/core/data/DateFormatISO8601.java
- data/org.eclipse.birt.core.script.function/src/org/eclipse/birt/core/script/function/bre/BirtDateTime.java
- data/org.eclipse.birt.core.script.function/src/org/eclipse/birt/core/script/function/bre/BreUtility.java
These commits try to fix the tests of the core plugin. One of the problems was the tests being dependent on the systems timezone / locale. My solution was to make the tests independent. Another solution would be to alter the system tz / locale in the maven build to the one the tests assume to be active (unclear what exactly it needs to be).
> Fix core tests

- core/org.eclipse.birt.core.tests/test/org/eclipse/birt/core/archive/AllArchiveTests.java
- core/org.eclipse.birt.core.tests/test/org/eclipse/birt/core/archive/BufferTest.java
Fixes a pending review comment of #590
> Convert TestBuffer to jUnit test case

- .github/workflows/ci.yml
Fixed to only build on push when pushed to master
> Pull request builds 2 times #612

- UI/org.eclipse.birt.report.designer.tests/src/org/eclipse/birt/report/designer/tests/example/matrix/TestingMatrixUI.java
- UI/org.eclipse.birt.report.designer.ui.data/src/org/eclipse/birt/report/designer/data/ui/dataset/ParameterComboCellEditor.java
- UI/org.eclipse.birt.report.designer.ui.views/src/org/eclipse/birt/report/designer/internal/ui/views/attributes/section/Section.java
- UI/org.eclipse.birt.report.designer.ui.views/src/org/eclipse/birt/report/designer/internal/ui/views/outline/providers/GridProvider.java
- UI/org.eclipse.birt.report.designer.ui.views/src/org/eclipse/birt/report/designer/internal/ui/views/outline/providers/RowProvider.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/data/ui/util/Utility.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/dialogs/ComboBoxMeasureFieldEditor.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/dialogs/DeleteWarningDialog.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/dialogs/EditableComboFieldEditor.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/dialogs/FormatChangeEvent.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/dialogs/StringFieldEditor.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/dnd/InsertInLayoutUtil.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/editors/schematic/tools/LibraryElementsToolHandleExtends.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/palette/PaletteCategory.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/palette/ReportTemplateTransferDropTargetListener.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/swt/custom/LayoutTable.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/swt/custom/TableArea.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/util/DataUtil.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/views/actions/AbstractGlobalSelectionAction.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/views/property/widgets/ComboBoxColorCellEditor.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/views/property/widgets/ComboBoxDimensionCellEditor.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/ui/widget/CTextCellEditor.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/ui/widget/ComboBoxCellEditor.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/ui/widget/ComboBoxExpressionCellEditor.java
Platform has removed this class. A drop-in replacement can be found in
o.e.core.runtime.
Replaced all occurrences
> Replace removed jface Assert for o.e.core.runtime.Assert #615

- UI/org.eclipse.birt.report.designer.ui.rcp/src/org/eclipse/birt/report/designer/ui/rcp/DesignerApplication.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/plugin/ReportExecutor.java
> Replace IPlatformRunnable for IApplication #617

- build/org.eclipse.birt.build/externalRepo.properties
- build/org.eclipse.birt.target/org.eclipse.birt.target.target
- data/org.eclipse.birt.report.data.oda.excel/META-INF/MANIFEST.MF
- data/org.eclipse.birt.report.data.oda.excel/src/org/eclipse/birt/report/data/oda/excel/impl/util/ExcelFileReader.java
- engine/org.eclipse.birt.report.engine.emitter.pptx.tests/META-INF/MANIFEST.MF
- engine/uk.co.spudsoft.birt.emitters.excel.tests/META-INF/MANIFEST.MF
- engine/uk.co.spudsoft.birt.emitters.excel.tests/src/uk/co/spudsoft/birt/emitters/excel/tests/Borders1ReportTest.java
- engine/uk.co.spudsoft.birt.emitters.excel.tests/src/uk/co/spudsoft/birt/emitters/excel/tests/Borders2ReportTest.java
- engine/uk.co.spudsoft.birt.emitters.excel.tests/src/uk/co/spudsoft/birt/emitters/excel/tests/Borders3ReportTest.java
- engine/uk.co.spudsoft.birt.emitters.excel.tests/src/uk/co/spudsoft/birt/emitters/excel/tests/Borders4ReportTest.java
- engine/uk.co.spudsoft.birt.emitters.excel.tests/src/uk/co/spudsoft/birt/emitters/excel/tests/GridsTests.java
- engine/uk.co.spudsoft.birt.emitters.excel.tests/src/uk/co/spudsoft/birt/emitters/excel/tests/HyperlinksTest.java
- engine/uk.co.spudsoft.birt.emitters.excel.tests/src/uk/co/spudsoft/birt/emitters/excel/tests/Issue27.java
- engine/uk.co.spudsoft.birt.emitters.excel.tests/src/uk/co/spudsoft/birt/emitters/excel/tests/Issue56FreezePanes.java
- engine/uk.co.spudsoft.birt.emitters.excel.tests/src/uk/co/spudsoft/birt/emitters/excel/tests/SimpleTableReportTest.java
- engine/uk.co.spudsoft.birt.emitters.excel/META-INF/MANIFEST.MF
- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/FilteredSheet.java
- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/FontManager.java
- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/StyleManager.java
- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/StyleManagerHUtils.java
- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/StyleManagerUtils.java
- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/StyleManagerXUtils.java
- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/CellContentHandler.java
- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/PageHandler.java
- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/TopLevelContentHandler.java
- releng/maps/orbit_bundles.map
- viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/web.xml
Update POI plugins to version 4.1.1 and add dependent plugins.
> POI Vulnerabilities #642

- model/org.eclipse.birt.report.model.tests/test/org/eclipse/birt/report/model/util/BaseTestCase.java
Determine why CI is failing in multiple pull requests and attempt to fix it.
> Determine why github CI is failing #655

- README.md
- UI/org.eclipse.birt.report.designer.ui.rcp/BIRT-headless.product
- UI/org.eclipse.birt.report.designer.ui.rcp/BIRT.product
- build/org.eclipse.birt.build/externalRepo.properties
- build/org.eclipse.birt.target/org.eclipse.birt.target.target
- chart/org.eclipse.birt.chart.device.pdf/META-INF/MANIFEST.MF
- features/org.eclipse.birt.chart.feature/feature.xml
- features/org.eclipse.birt.chart.osgi.runtime/feature.xml
- features/org.eclipse.birt.engine.runtime/feature.xml
- features/org.eclipse.birt.feature/feature.xml
- features/org.eclipse.birt.osgi.runtime/feature.xml
- features/org.eclipse.birt.report.designer.editor.xml.wtp.feature/feature.xml
- releng/maps/orbit_bundles.map
- testsuites/org.eclipse.birt.report.tests.engine/src/org/eclipse/birt/report/tests/engine/api/RenderTaskTest.java
- viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/web.xml
Update batik plugins to version 1.14.
> Batik vulnerabilities #651

- build/org.eclipse.birt.target/org.eclipse.birt.target.target
- viewer/org.eclipse.birt.report.viewer/jettyhome/etc/jetty.xml
Fixed jetty.xml some methods were removed
from gziphandler
Issue: #649
> Report viewer failing again.

- README.md
- build/org.eclipse.birt.releng/BIRT.setup
- build/org.eclipse.birt.releng/BIRTConfiguration.setup
Ed @merks kindly created `BIRTConfiguration.setup` and improved
`BIRT.setup`
Link in README.MD should point to `BIRTConfiguration.setup`
> BIRT Eclipse Installer gives error message #690

- UI/org.eclipse.birt.report.designer.ui.views/src/org/eclipse/birt/report/designer/internal/ui/views/attributes/provider/StyleComboProvider.java
- UI/org.eclipse.birt.report.designer.ui.views/src/org/eclipse/birt/report/designer/internal/ui/views/attributes/widget/DualRadioButtonPropertyDescriptor.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/editors/parts/GraphicalEditorWithFlyoutPalette.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/swt/custom/StyleCombo.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/swt/custom/TabbedPropertyList.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/util/graphics/ImageCanvas.java
- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/ui/util/UIUtil.java
> Resource leaks #707

- build/org.eclipse.birt.target/org.eclipse.birt.target.target
> "Orbit latest" updated, missing dependencies in target platform

- UI/org.eclipse.birt.report.debug.ui/src/org/eclipse/birt/report/debug/internal/ui/launcher/util/ReportLauncherUtils.java
- UI/org.eclipse.birt.report.debug.ui/src/org/eclipse/birt/report/debug/ui/launching/ReportAdvancedLauncherTab.java
Removed unused and 16 year old dead code.
Almost all the scary stuff in this class was unused if the dead code in getAutoStartPlugins() was removed. That if(true) statement was introduced a looong time ago.
> Review ReportLauncherUtils.java: #671

- pom.xml
Added environments to the parent-pom.xml and
> Build for multiple targets #729

- .github/workflows/ci.yml
> Archive build artifacts #730

- build/org.eclipse.birt.releng.birtbuilder/extras/genReport.bat
* Added help
* Classpath issues were resolved
* Made the script OSGi aware
> Fix report runner windows batch file #799

- pom.xml
>  Building birt for aarch64 mac #810 

- common/javax.xml.rpc/.project
Update .project file of rpc plugin
> Move projects to Java 11 #672

- UI/org.eclipse.birt.report.designer.ui.rcp/BIRT-headless.product
- UI/org.eclipse.birt.report.designer.ui.rcp/BIRT.product
- build/org.eclipse.birt.target/BIRT Chart Test.launch
- build/org.eclipse.birt.target/BIRT Model Test.launch
- build/org.eclipse.birt.target/BIRT all-in-one-MAC.launch
- build/org.eclipse.birt.target/BIRT all-in-one.launch
- build/org.eclipse.birt.target/org.eclipse.birt.target.target
- engine/org.eclipse.birt.report.engine.emitter.odp/META-INF/MANIFEST.MF
- engine/org.eclipse.birt.report.engine.emitter.pdf/META-INF/MANIFEST.MF
- engine/org.eclipse.birt.report.engine.emitter.postscript/META-INF/MANIFEST.MF
- engine/org.eclipse.birt.report.engine.emitter.ppt/META-INF/MANIFEST.MF
- engine/org.eclipse.birt.report.engine.emitter.pptx/META-INF/MANIFEST.MF
- engine/org.eclipse.birt.report.engine.emitter.wpml/META-INF/MANIFEST.MF
- engine/org.eclipse.birt.report.engine.tests/META-INF/MANIFEST.MF
- engine/org.eclipse.birt.report.engine/META-INF/MANIFEST.MF
- features/org.eclipse.birt.engine.runtime/feature.xml
- features/org.eclipse.birt.feature/feature.xml
- features/org.eclipse.birt.osgi.runtime/feature.xml
- features/org.eclipse.birt.rcp.feature/feature.xml
- features/org.eclipse.birt.report.designer.editor.xml.wtp.feature/feature.xml
This is an attempt to do a cleaner solution to #767 and, if it compiles, it will replace #780
> Replace iText with OpenPDF #767

- CODE_OF_CONDUCT.md
- NOTICES
- SECURITY.md
Added files to main branch per request of EMO.
> NOTICES, Code of Conduct, and Security statement added for release review. 

- features/org.eclipse.birt.engine.runtime/feature.xml
Will ant pick this bundle up from the plugins folder?
> Not able to create StateObjectFactory impl. #836

- nl/org.eclipse.birt.data.oda.pojo.ui.nl/.project
- nl/org.eclipse.birt.data.oda.pojo.ui.nl/pom.xml
> Up version numbers to 4.10 #883

- .github/workflows/ci.yml
> Disable pull_request_target #894

- build/org.eclipse.birt.p2updatesite/category.xml
@wimjongman I think this should be sufficient. It's not really a contribution.
It adds the rcp feature to the updatesite. This should fix #879
> add rcp feature to the updatesite

- UI/org.eclipse.birt.report.debug.ui/src/org/eclipse/birt/report/debug/internal/script/model/ScriptDebugTarget.java
- UI/org.eclipse.birt.report.debug.ui/src/org/eclipse/birt/report/debug/internal/ui/script/launcher/ReportDebuggerVMRunner.java
- UI/org.eclipse.birt.report.debug.ui/src/org/eclipse/birt/report/debug/internal/ui/script/launcher/ReportOSGiLaunchDelegate.java
- UI/org.eclipse.birt.report.debug.ui/src/org/eclipse/birt/report/debug/internal/ui/script/launcher/ScriptLaunchShortcut.java
- UI/org.eclipse.birt.report.debug.ui/src/org/eclipse/birt/report/debug/internal/ui/script/launcher/StandardScriptVMRunner.java
Removed deprecated call
Code cleanup
Debug job can now be canceled when looping in listen mode
> Update manager not supported with debug configuration #907 #909

- .github/workflows/ci.yml
- data/org.eclipse.birt.data.tests/pom.xml
- data/org.eclipse.birt.data.tests/test/org/eclipse/birt/data/engine/binding/FeaturesTest.java
- data/org.eclipse.birt.data.tests/test/org/eclipse/birt/data/engine/executor/cache/golden/CacheComputedColumnTest.testTopNAggregationOnComputedColumnWithFilterOnEmptyDataSet.txt
- data/org.eclipse.birt.data.tests/test/org/eclipse/birt/data/engine/executor/cache/golden/CacheComputedColumnTest.testTopNPercentAggregationOnComputedColumnWithFilterOnEmptyDataSet.txt
- data/org.eclipse.birt.data.tests/test/org/eclipse/birt/data/engine/olap/cursor/CursorNavigatorTest.java
- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/api/querydefn/Binding.java
- data/org.eclipse.birt.data/src/org/eclipse/birt/data/engine/executor/DataSourceQuery.java
> Fix data regression tests

- build/org.eclipse.birt.build/.classpath
- build/org.eclipse.birt.build/META-INF/MANIFEST.MF
Removed the "Export-Package" headers for dom4j packages.
> Build fails with "Missing dom4j messages" #952

- build/org.eclipse.birt.target/org.eclipse.birt.target.target
Switched to the last known good repo
> Latest Orbit repository has dropped a lot of bundles #986

- build/org.eclipse.birt.releng/BIRT.setup
https://github.com/eclipse/birt/discussions/1060
> Fix BIRT.setup to avoid installing unsupported m2e connectors

- viewer/org.eclipse.birt.report.viewer.tests/test/org/eclipse/birt/report/context/ViewerAttributeBeanTest.java
- viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/context/ViewerAttributeBean.java
Fixed validity of the document parameter.
> Fix document output file #1118

- chart/org.eclipse.birt.chart.examples/src/org/eclipse/birt/chart/examples/view/ChartExamples.java
- chart/org.eclipse.birt.chart.examples/src/org/eclipse/birt/chart/examples/view/ChartExamplesView.java
- chart/org.eclipse.birt.chart.examples/src/org/eclipse/birt/chart/examples/view/util/ItemContentProvider.java
Fixed the examples so that they can run without platform running
> Chart examples don't run standalone #1153

- chart/org.eclipse.birt.chart.engine/customBuildCallbacks.xml
- chart/org.eclipse.birt.chart.engine/pom.xml
properties file is not included when creating the chartitemapi jar file.
> Opening report design containing a chart with design session is failing

- viewer/org.eclipse.birt.report.viewer/META-INF/MANIFEST.MF
Fixed https://github.com/eclipse-birt/birt/issues/1301
> Ensure that com.sun.el is available for report preview functionality

- Jenkinsfile
- testsuites/org.eclipse.birt.report.tests.chart/src/org/eclipse/birt/report/tests/chart/regression/Regression_134885.java
https://github.com/eclipse-birt/birt/issues/1286
> Conditionally disable test that fails running on centos

- common/org.apache.batik.dom.birt.ext/pom.xml
- common/org.apache.batik.transcoder.birt.ext/pom.xml
- common/org.w3c.dom.svg.extension/pom.xml
- model/org.eclipse.birt.report.model.tests/pom.xml
- testsuites/org.eclipse.birt.report.tests.model/pom.xml
https://github.com/eclipse-birt/birt/issues/1286
> Eliminate the blocking of signing

- build/org.eclipse.birt.releng/BIRT.setup
- build/org.eclipse.birt.target/org.eclipse.birt.target.target
- promotion/pom.xml
Use images from the website for the update site images.
https://github.com/eclipse-birt/birt/issues/1286
> Use an orbit legacy repo with PGP-signed content

- build/org.eclipse.birt.releng/BIRT.setup
- build/org.eclipse.birt.target/org.eclipse.birt.target.target
This is to help  ensure that when possible to get the PGP signed artifact from legacy repository
https://github.com/eclipse-birt/birt/issues/1286
> Reorder the repositories for the target

- build/birt-packages/birt-report-all-in-one/BIRT.product
- build/org.eclipse.birt.target/org.eclipse.birt.target.target
Regenerate the target platform accordingly.
https://github.com/eclipse-birt/birt/pull/1364
> Update BIRT.product to use the latest Mylyn feature IDs

- build/org.eclipse.birt.releng/BIRT.setup
- build/org.eclipse.birt.target/org.eclipse.birt.target.target
Also regenerate the target platform accordingly.
> Update the setup to use a non-broken WTP repository

- build/org.eclipse.birt.releng/BIRT.setup
- build/org.eclipse.birt.target/org.eclipse.birt.target.target
Also regenerate the target platform accordingly.
> Update the setup to use the repaired WTP latest release repository

- .github/workflows/ci.yml
Added github action to clean up cached data and log data (#1425)
> Added github action to clean up cached data and log data (#1425)

- .github/workflows/ci.yml
- engine/org.eclipse.birt.report.engine.emitter.html/src/org/eclipse/birt/report/engine/emitter/html/HTMLReportEmitter.java
- engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/AbstractEmitterImpl.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/emitter/ImageReader.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/util/SvgFile.java
- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/AbstractRealTableCellHandler.java
- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/CellContentHandler.java
The changes fix the 3 topics of the issue-ticket #1416
> Improved handling of space characters at file-url and svg-images base64-encoded (#1416)

- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/TopLevelTableHandler.java
Fix issue with spudsoft auto filter to avoid cell range issue (#998)
> Fix issue with spudsoft auto filter to avoid cell range issue (#998)

- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/AbstractHandler.java
- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/AbstractRealTableCellHandler.java
- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/FlattenedListHandler.java
Excel, Spudsoft - Improvement the list element handling #1432 
- AbstractRealTableCellHandler, fixed class cast issues
- FlattenedListHandler, added missing (override) methods
- AbstractHandler, comment out error handling because the list container- & content-elements haven't a specific implementation
> Excel, Spudsoft, Improvement of the list element handling (#1432)

- UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/util/ImageManager.java
Fix variable mis-switch so that images will be displayed correctly (#1437)
> Fix variable mis-switch so that images will be displayed correctly (#1437)

- engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/PDFPage.java
- engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/PDFPageDevice.java
PdfEmitter, Enhancement: Enable options to set the PDF/Version & archiving formats PDF/A (A1A & A1B) #1486
>  PdfEmitter, Enhancement: Enable options to set the PDF/Version & archiving formats PDF/A (A1A & A1B) #1486 

- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/StyleManagerUtils.java
- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/AbstractRealTableRowHandler.java
Fix excel issue to set the row height and column width of unit "px" correctly (#1496)
> Fix excel issue to set the row height and column width of unit "px" correctly (#1496)

- engine/org.eclipse.birt.report.engine.emitter.pptx/src/org/eclipse/birt/report/engine/emitter/pptx/TableWriter.java
Change the ID calculation to get the next table cell.
> Fix issue with PPTX right border (#1537)

- UI/org.eclipse.birt.report.designer.core/src/org/eclipse/birt/report/designer/util/ImageManager.java
- engine/org.eclipse.birt.report.engine.emitter.wpml/src/org/eclipse/birt/report/engine/emitter/wpml/AbstractEmitterImpl.java
Fix image issue with docx (#1549) and eclipse preview (#1550)
> Fix image issue with docx (#1549) and eclipse preview (#1550)

- UI/org.eclipse.birt.report.designer.ui/plugin.xml
Added color definition of syntax highlighter
> Added color definition of syntax highlighter

- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/nLayout/area/style/BackgroundImageInfo.java
Remove the error stack trace print (#1595)
> Remove the error stack trace print (#1595)

- .github/workflows/ci.yml
https://github.com/eclipse-birt/birt/issues/1614
> Disable artifact archiving from ci.yml

- UI/org.eclipse.birt.report.designer.ui/src/org/eclipse/birt/report/designer/internal/ui/script/JSPartitionScanner.java
Enhance the syntax highlighter of the javascript add additional objects (#1570)
> Enhance the syntax highlighter of the javascript add additional objects (#1570)

- viewer/org.eclipse.birt.report.viewer/src/org/eclipse/birt/report/viewer/utilities/ViewerWebApp.java
Enhance designer viewer with spaces into path (#1466)
> Enhance designer viewer with spaces into path (#1466)

- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/AbstractRealTableCellHandler.java
xlsx, enhanced the validation of embedded cell objects
> xlsx, enhanced the validation of embedded cell objects

- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/PageHandler.java
fix range values of the user property ExcelEmitter.PrintScale (#1649)
> fix range values of the user property ExcelEmitter.PrintScale (#1649)

- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/ExcelEmitter.java
- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/README.md
enhance the excel emitter with force recalculation option (#1651)
> Enhance the excel emitter with force recalculation option (#1651)

- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/ExcelEmitter.java
- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/README.md
- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/AbstractRealListHandler.java
- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/AbstractRealTableHandler.java
- engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/handlers/PageHandler.java
Enhance the options to setup the excel preview (#1658)
> Enhance the options to setup the excel preview (#1658)

- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/BIRTCSSEngine.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/CSSContext.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/CSSEngine.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/CSSStylableElement.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/PerfectHash.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/PropertyManagerFactory.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/SystemColorSupport.java
- engine/org.eclipse.birt.report.engine/src/org/eclipse/birt/report/engine/css/engine/ValueManager.java
- model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/css/CSSValue.java
- model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/css/CssParser.java
- model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/css/CssStyle.java
- model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/css/CssStyleSheet.java
- model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/css/CssStyleSheetAdapter.java
- model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/css/CssStyleSheetHandleAdapter.java
- model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/css/Property.java
- model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/css/StyleDeclaration.java
- model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/css/StyleRule.java
- model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/css/StyleSheetLoader.java
- model/org.eclipse.birt.report.model/src/org/eclipse/birt/report/model/css/property/PropertyParser.java
Fix eclipse warnings and add java documentation (#1670)
> Fix eclipse warnings and add java documentation (#1670)

- core/org.eclipse.birt.core/src/org/eclipse/birt/core/script/JavascriptEvalUtil.java
- data/org.eclipse.birt.report.engine.script.javascript/src/org/eclipse/birt/report/engine/javascript/JavascriptEngine.java
- data/org.eclipse.birt.report.engine.script.javascript/src/org/eclipse/birt/report/engine/javascript/JavascriptEngineFactory.java
- data/org.eclipse.birt.report.engine.script.javascript/src/org/eclipse/birt/report/engine/javascript/JavascriptVersion.java
- data/org.eclipse.birt.report.engine.script.javascript/src/org/eclipse/birt/report/engine/javascript/README.md
- data/org.eclipse.birt.report.engine.script.javascript/src/org/eclipse/birt/report/engine/javascript/ScriptUtil.java
Remove the deprecated security manager and add a JVM-birt system property for activation (#1778)
> Remove the deprecated security manager and add a JVM-birt system property for activation (#1778)

- build/org.eclipse.birt.releng/BIRT.setup
Fixes https://github.com/eclipse-birt/birt/issues/1320
> Include website clone in the project setup

- UI/org.eclipse.birt.report.designer.ui.ide/src/org/eclipse/birt/report/designer/ui/ide/wizards/NewReportWizard.java
When a new report is created, the first step is to add a data source and data set.
> Show the DataView when a new report is created #1738

- build/birt-packages/birt-runtime/build.xml
- build/org.eclipse.birt.build/src/org/eclipse/birt/build/ant/PackTask.java
- build/org.eclipse.birt.releng/BIRT.setup
https://github.com/eclipse-birt/birt/issues/1819
> Ensure that org.eclipse.birt.build.ant.PackTask filters out CODESIGN.*

- build/org.eclipse.birt.releng.birtbuilder/extras/genReport.bat
- build/org.eclipse.birt.releng.birtbuilder/extras/genReport.sh
- build/org.eclipse.birt.releng.birtbuilder/extras/runtime_readme.txt
Fixed the runtime scripts for a better OOTB experience.
>  Fix the runtime example scripts #1944

- engine/org.eclipse.birt.report.engine.emitter.pdf/src/org/eclipse/birt/report/engine/emitter/pdf/PDFPage.java
This fixes #1951.
By the way: The author hvbargen is me, too.
I'm using that account for hobby projects, whereas I use hvbtup at work.
> Fix PDF syntax error (cm not allowed after BT)

- viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/service/ReportEngineService.java
- viewer/org.eclipse.birt.report.viewer/birt/WEB-INF/classes/org/eclipse/birt/report/utility/BirtUtility.java
The implementation is done for the both processing task:
- RunAndRender-task
- Run-task
The handling of the parameters and the display text is different. Additional on it the assignment of the display text is enhanced so that the result of the display text can be a string-array which was already implemented but never used.
For the internal handling I used a ArrayList<String> with will be converted to a standard string-array.
> Enhance display text for multi selections (#1981)

- build/birt-packages/birt-report-all-in-one/pom.xml
- build/birt-packages/birt-runtime-osgi/pom.xml
- pom.xml
- Use storeCreationTime to avoid LIBARCHIVE.creationtime tar.gz warnings
> Use Tycho 4.0.10

- core/org.eclipse.birt.core/src/org/eclipse/birt/core/util/CommonUtil.java
https://github.com/eclipse-birt/birt/issues/1986
> Disable entity-related security features in CommonUtil.createSAXParser

- build/org.eclipse.birt.releng/BIRT.setup
- build/org.eclipse.birt.target/org.eclipse.birt.target.target
https://github.com/eclipse-birt/birt/issues/1910
> Update the setup and the target platform for datatools permanent sites

- build/org.eclipse.birt.releng/BIRT.setup
- build/org.eclipse.birt.target/org.eclipse.birt.target.target
- pom.xml
- Use Tycho 4.0.12 and CBI 1.5.2.
https://github.com/eclipse-birt/birt/issues/1997
> Update the setup and the target platform to specify permanent sites

- build/org.eclipse.birt.releng.maven/.project
- build/org.eclipse.birt.releng.maven/BIRT-Runtime-Minimized.aggr
- build/org.eclipse.birt.releng.maven/BIRT-Runtime-Minimized.aggran
- build/org.eclipse.birt.releng.maven/BIRT-Runtime.aggr
- build/org.eclipse.birt.releng.maven/BIRT-Runtime.aggran
- build/org.eclipse.birt.releng/BIRT.setup
- Update the setup to install the CBI aggregator editors.
https://github.com/eclipse-birt/birt/issues/625
> Provide *.aggr and corresponding *.aggran for Maven publishing

- build/org.eclipse.birt.releng.maven/BIRT-Runtime-Minimized.aggr
- build/org.eclipse.birt.releng.maven/BIRT-Runtime.aggr
- Add maven-wrapped-<groupId|artifactId|version> as fallback
- Add mapping for apache derby
- Fix uk.co.spudsoft.birt.emitters.excel version
https://github.com/eclipse-birt/birt/issues/625
> Update *.aggr for Maven publishing

- build/org.eclipse.birt.releng.maven/BIRT-Runtime.aggr
- build/org.eclipse.birt.releng.maven/BIRT-Runtime.aggran
- build/org.eclipse.birt.releng.maven/publishToMaven.jenkinsfile
- build/org.eclipse.birt.releng/BIRT.setup
https://github.com/eclipse-birt/birt/issues/625
> Support Maven publishing

- viewer/org.eclipse.birt.report.viewer/birt/webcontent/birt/ajax/ui/app/BirtToolbarTheme.js
- theme cookie with expiration time and set default theme to "light" theme
> Enhance dark theme cookie with expiration time

- UI/org.eclipse.birt.report.designer.ui.editors/src/org/eclipse/birt/report/designer/internal/ui/views/outline/DesignerOutlinePage.java
https://github.com/eclipse-birt/birt/pull/2122
> Open the search dialog using Ctrl-F via a keyboard listener
